### ISSUE TITLE
Support deployment preview

### ISSUE THREAD

**Issue by dylan-glenn** [oracle/netsuite-suitecloud-sdk#100]
In the Java version of the SuiteCloud CLI, there is a preview command that allows you to preview all of the deployment steps for an SDF project.

The key aspect of this functionality for our current processes is the ability to view all of the Objects/Files that will be uploaded/updated in the destination account.

Does the Node.js version support this functionality? If so, how is it achieved? If not, is this on the roadmap for this tool?

**Comment by vic-nik** [comment]
This is not currently supported by SuiteCloud CLI and there's no plan to introduce this command at this point. We will consider adding this feature and will keep this issue open until we have more updates.

**Comment by wulfmann** [comment]
i would like to just add that i'd love this feature!

**Comment by Xmun88** [comment]
me too!

**Comment by alii-gator** [comment]
This is already available in new version `1.2.0`
Install the new version and check it out
