### ISSUE TITLE
suitecloud account:setup fails on case of letters in account ID

### ISSUE THREAD

**Issue by NSAcctFinder** [oracle/netsuite-suitecloud-sdk#102]
I was trying to stand up a new SDF project. My Account ID is  like "tstdrv1234567". 

First attempt failed, when I specified that account ID as NetSuite shows it in the URL bar in my browser - with tstdrv in lower case letters. 

`
C:\workspaces\test-cli\test-cli>suitecloud account:setup
? Select an authentication method: Save a TBA token issued in NetSuite.
? Enter an authentication ID (authID): authID1
? Enter the account ID: **tstdrv1234567**
? Enter the Token ID: ****************************************************************
? Enter the Token Secret: ****************************************************************
The token could not be validated. The authentication details are not valid or the server could not respond. Review your authentication details and try again.
Error details:
Invalid login attempt.
`

Second attempt was successful - when I specified the account ID with upper case letters, as a guess. 

`C:\workspaces\test-cli\test-cli>suitecloud account:setup -i
? Select an authentication method: Save a TBA token issued in NetSuite.
? Enter an authentication ID (authID): authID1
? Enter the account ID: **TSTDRV1234567**
? Enter the Token ID: ****************************************************************
? Enter the Token Secret: ****************************************************************
The TBA token has been saved for the following company and role: ^^^SuiteCloud Developer Exam [Administrator]. This project will use the authentication ID as default. If you want to change your default credentials, run "suitecloud account:setup" again.
The account has been successfully set up.`

Ideally, the tool would convert those 'tstdrv' letters to upper case for me, so it doesn't fail with an error message that is hard to make sense of.  Thanks,

**Comment by alii-gator** [comment]
Thanks for bringing it up @NSAcctFinder 
This is something which can be handled at CLI level. We are looking into it.
Will update you as soon as we have any new about it.

**Comment by alegomez** [comment]
Hi there, I've been struggling to find the authID, @NSAcctFinder could you point me in the right direction?
cheers!

**Comment by alii-gator** [comment]
@alegomez authid is a user defined string. Just like an alias for the token.

**Comment by alegomez** [comment]
thank you very much indeed, I reckon my authentication problem lies somewhere else.
cheers

**Comment by alegomez** [comment]
I'm currently using the "account ID" found under Setup > Company > Company Information and the same token ID and token secret as in every SOAP request (and RESTLets for that matter)... sadly the token cannot be validated, any ideas?

**Comment by alii-gator** [comment]
@alegomez You need to check following 2 things

1. when you generate the token from UI, are you selecting this application -> "Suitecloud Development Integration"
![image](https://user-images.githubusercontent.com/28846677/83268515-081df900-a1c6-11ea-9670-9933380597c9.png)
2. The accountID, doest it contain any aplhabets? if YES then when you input it in cli, make sure its in upper case.

**Comment by alegomez** [comment]
That did the trick, thanks a lot!
cheers!

**Comment by alii-gator** [comment]
@alegomez we have improved this.
The tools will handle this automatically. 
Hole fully in the upcoming versions you will see the improvements.

**Comment by alii-gator** [comment]
@NSAcctFinder 
This is now fixed/available in latest version 
get the latest npm package version `1.1.0`

**Comment by anshulgupta4** [comment]
@alii-gator -- 
/bin/bash ${WORKSPACE}/build/sdfcli.sh authenticate -savetoken -tokenid $NS_TOKENID -tokensecret $NS_TOKENSECRET -account $NS_ACCOUNT -authid deployme
I run the above command but keep getting the below error.The token id and secret have been generated correctly.
Where is the glitch ?? 
_"The token could not be validated. The authentication details are not valid or the server could not respond. Review your authentication details and try again."_

**Comment by vic-nik** [comment]
Hi Anshul,
I think the error is self explanatory. Either your token details are invalid/expired/inactive or the CLI is not able to make a request to the NetSuite due to network problem. Also you are using Java CLI in your example and this GitHub repository is for Node JS CLI. Anyways they work in a similar way and it will work with valid token details and proper network access setup.

**Comment by alii-gator** [comment]
@anshulgupta4 Make sure when you generate the token from UI, you select SuiteCloud Development Integration from the application name dropdown. Otherwise token will not work.

**Comment by anshulgupta4** [comment]
@alii-gator -- This was the reason why i was not able to login . Thanks was able to login the account !!

**Comment by salvo4u** [comment]
@alii-gator 
I logged into netsuite and generated keys and issued a authid for myself that i want to use for deployments
_./sdfcli.sh authenticate -savetoken -tokenid abc -tokensecret xyz -account 123456 -authid mykey_
But when i use mykey with the deploy command is gives me the error:
_/bin/bash ${WORKSPACE}/build/sdfcli.sh validate -p ../$line  -authid scjprod1 -server_

**_"The "********" authentication ID (authID) is not available. Check your authentication credentials and try again."_**

How can this be removed ??

**Comment by WendyYang77** [comment]
> @alegomez You need to check following 2 things
> 
> 1. when you generate the token from UI, are you selecting this application -> "Suitecloud Development Integration"
>    ![image](https://user-images.githubusercontent.com/28846677/83268515-081df900-a1c6-11ea-9670-9933380597c9.png)
> 2. The accountID, doest it contain any aplhabets? if YES then when you input it in cli, make sure its in upper case.

Hi @alii-gator 

when I generate token from UI, I can't select role - Administrator.  Is Admin role required? 
the authentication failed like : The token could not be validated. The authentication details are not valid or the server could not respond. Review your authentication details and try again.
Error details: Invalid login attempt.

Any thoughts would be appreciated.

**Comment by WendyYang77** [comment]
> @alegomez You need to check following 2 things
> 
> 1. when you generate the token from UI, are you selecting this application -> "Suitecloud Development Integration"
>    ![image](https://user-images.githubusercontent.com/28846677/83268515-081df900-a1c6-11ea-9670-9933380597c9.png)
> 2. The accountID, doest it contain any aplhabets? if YES then when you input it in cli, make sure its in upper case.

Hi @alii-gator 

I tried to set up an account in VS Code for Sandbox, and failed to gat the authentication right.
My sandbox domain is : 123456-sb1.app.netsuite.com
in this case, my account id is 123456 or 123456-SB1?  I tried both but with no luck.

The error is like : 
_The token could not be validated. The authentication details are not valid or the server could not respond. Review your authentication details and try again. Error details: Invalid login attempt._

Thanks if you can shed some light here.

**Comment by WendyYang77** [comment]
> > @alegomez You need to check following 2 things
> > 
> > 1. when you generate the token from UI, are you selecting this application -> "Suitecloud Development Integration"
> >    ![image](https://user-images.githubusercontent.com/28846677/83268515-081df900-a1c6-11ea-9670-9933380597c9.png)
> > 2. The accountID, doest it contain any aplhabets? if YES then when you input it in cli, make sure its in upper case.
> 
> Hi @alii-gator
> 
> I tried to set up an account in VS Code for Sandbox, and failed to get the authentication right. My sandbox domain is : 123456-sb1.app.netsuite.com in this case, my account id is 123456 or 123456-SB1? I tried both but with no luck.
> 
> The error is like : _The token could not be validated. The authentication details are not valid or the server could not respond. Review your authentication details and try again. Error details: Invalid login attempt._
> 
> Thanks if you can shed some light here.

Finally sort out SB domain is the same as production, and the  account ID is  123456_SB1 ( underline works, and dash doesn't even it is a dash in URL)
