### ISSUE TITLE
Need to switch Accounts from CLI

### ISSUE THREAD

**Issue by grugknuckle** [oracle/netsuite-suitecloud-sdk#112]
This is request for an enhancement or an explanation of how to use a hidden feature. 

When using the CLI tool, I am unable to control which NetSuite account the CLI is communicating with. For example, I need to be able to do things like the following ...

`suitecloud object:import --type ALL --account <my SANDBOX account id>`

and then

`suitecloud project:deploy --account <my PRODUCTION account id>`

In issue #21 , it was mentioned that the account could be controlled via the `account.json` file which is no longer present in the project. However, there is a `suitecloud.config.js` file. If the default account is modifiable via the `suitecloud.config.js` file, then an improved documentation of how to do that is required.

### My environment
OS: Windows 10
Node.js version: e.g. 12.16.1
suitecloud-cli version: 1.0.2
Terminal/CMD tool: I use PowerShell, VSCodeTerminal and the native windows command prompt.

**Comment by alii-gator** [comment]
Hi @grugknuckle 
account.json is deprecated. That was before we officially released.

Now the file which is used to contain the default project is called `project.json`
This file will be automatically generated if you run `suitecloud setup:account` and then you will have 2 options.

- Select one of the exisiting authid
- Complete the authentication flow  

Everytime you want to change the default account. Run suitecloud account:setup inside your project and select the authID(account) you want to use. That will be set as your project until you change it.

**Comment by alii-gator** [comment]
You can find this information in read.me file of suitecloud-cli.
Please try it out, and if you any doubts let me know. once you confirm it's working for you, i will close this issue.

**Comment by grugknuckle** [comment]
Thank you @alii-gator. There was some initial confusion about the authId naming. But it's working now. Is there a way to remove / rename existing roles for an existing project?

**Comment by alii-gator** [comment]
@grugknuckle this feature is under development. Hopefully should be available in next release.
If your original question is resolved i will close this issue. If you have anu further problems please open a new issue.
