### ISSUE TITLE
Unable to list plug-in implementations

### ISSUE THREAD

**Issue by 0xbboyd** [oracle/netsuite-suitecloud-sdk#113]
### Your environment
**OS** : Fedora 31
**Node.js version** : 12.16.3
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : zsh

### Describe the bug
The cli does not list plug-in implementations that are visible in the account UI.

### To Reproduce
1. suitecloud object:list -i
2. Do you want to list all object types? No
3. Select the object types you want to list. Plug-in - Custom Plug-in Implementation
4. Do you want to enter a script ID to filter your list? No

### Actual Behavior
![Selection_266](https://user-images.githubusercontent.com/1747303/81228117-59a9de00-8fa2-11ea-9602-362edac16d9f.png)

![Selection_267](https://user-images.githubusercontent.com/1747303/81228153-67f7fa00-8fa2-11ea-9930-df7ebd710421.png)

### Expected Behavior
List all plugin implemenations available in the account.

**Comment by alii-gator** [comment]
@firemound Thanks for the detailed explanation. 
I am checking it and will get back with more information/questions soon.

**Comment by alii-gator** [comment]
@firemound 
I think there is a mis match in the objects **type** you are trying to list and the ones in account.
Can you select all plugin options in **step 3** and see if the ones listed in screenshot from UI, appear, and if they do what is the type?

**Comment by firemound** [comment]
Hi @alii-gator, as you can see, only the plugin type is listing — not the plugin implementations. 

![Selection_268](https://user-images.githubusercontent.com/1747303/81357047-8edc2c00-9087-11ea-8a9e-b628248385fb.png)

Thanks for the follow up.

**Comment by firemound** [comment]
Selecting all plugin types, the plugin implementations are missing:

![Selection_269](https://user-images.githubusercontent.com/1747303/81358614-e2e90f80-908b-11ea-9e76-e8f0af0a7955.png)

**Comment by alii-gator** [comment]
@firemound is there any chance that the expected plugin implementation objects were deployed with a suiteapp?

**Comment by firemound** [comment]
1. No, they are all part of an account customization project and not part of a bundle.
2. Yes, I'm able to download objects using this authid that currently only exist in our sb1 account.
3. Yes, that is correct, only 6 results are shown. The next line is cut off because I had executed more commands after these results printed out.

**Comment by alii-gator** [comment]
@0xbboyd Can you please confirm if you still have this issue in the latest version of the tool!

**Comment by lfpvillegas** [comment]
Close due to inactivity. Please reopen the issue if you continue to have the same behavior.
