### ISSUE TITLE
security vulnerabilities in localserver-cli-command dependency

### ISSUE THREAD

**Issue by ori-moisis** [oracle/netsuite-suitecloud-sdk#115]
The [localserver-cli-command package](https://github.com/oracle/netsuite-suitecloud-sdk/blob/master/extensions/localserver-cli-command/package.json) depends on a specific and old version of the package 'handlebars'.
That old version has a dependency on the discontinued `optimist` which uses a package called `minimist` that has a [known security vulnerability](https://github.com/advisories/GHSA-vh95-rmgr-6w4m)

It would be nice if the dependencies could be updated to newer versions (or, generally, allow newer versions instead of locking everything to a specific version)

**Comment by alii-gator** [comment]
Thanks @ori-moisis for bringing this up.
Surely we will look in to this Asap.

**Comment by alii-gator** [comment]
Fixed in latest version.
