### ISSUE TITLE
project:adddependencies command adds features that doesn't exist

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#124]
### Your environment
**OS** : iOS Catalina 10.15.4
**Node.js version** : 13.13.0
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : iTerm2

### Describe the bug
project:adddependencies command adds features that doesn't exist.
For example, when editing a transactionForm, the following features are added as a dependency:
`NOTTAX_OVERHAULING`, `VATNOTTAX_OVERHAULING`, `DOCUMENTS`, `VATORTAX_OVERHAULING`, `PERLINETAXNOTTAX_OVERH`
When triggering project:deploy command right after, I receive the below for each of the above dependencies:
>  Details: The NOTTAX_OVERHAULING feature defined in the manifest does not exist.

### To Reproduce
1. Add the attached transactionForm XML to the project - [custform_6_2239021_717.txt](https://github.com/oracle/netsuite-suitecloud-sdk/files/4677577/custform_6_2239021_717.txt) (modify to .xml)
2. Run suitecloud project:adddependencies
3. Run suitecloud project:deploy

### Actual Behavior
Receiving the below error:
> Details: The NOTTAX_OVERHAULING feature defined in the manifest does not exist.

### Expected Behavior
Deploy should succeed

**Comment by alii-gator** [comment]
@omrilit we are checking it, will get back to you soon with our findings.

**Comment by omrilit** [comment]
@alii-gator any updates on this one?

**Comment by alii-gator** [comment]
@omrilit We have started working on this at priority bases. We will have update soon.

**Comment by dspadea-9w** [comment]
Another for the investigation:

project:validate told us:

 Line No. 1 - Error Message: The following dependencies are missing from the manifest.xml file: [Feature - WMSSYSTEM:required]

But upon adding it via project:adddependencies:

 Error Message: The "WMSSYSTEM" feature defined in the manifest does not exist.

**Comment by alii-gator** [comment]
@omrilit Can you please verify this in latest version 1.1.0?

**Comment by omrilit** [comment]
Seems like this bug is indeed resolved in this version, but the same attached transactionForm still produces some errors upon deploy. I will open a separate ticket on it.

**Comment by alii-gator** [comment]
@omrilit Thanks for confirmation.
Yes, there are some issues still being worked on. Feel free to open the a new ticket.
