### ISSUE TITLE
project:adddependencies command doesn't add required features to the manifest for workflow records

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#128]
### Your environment
**OS** : iOS Catalina 10.15.4
**Node.js version** : 13.13.0
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : iTerm2

### Describe the bug
project:adddependencies command doesn't add required features to the manifest for workflow records.

### To Reproduce

Add the attached workflow XML to the project - [customworkflow1.txt](https://github.com/oracle/netsuite-suitecloud-sdk/files/4687101/customworkflow1.txt) (modify to .xml)
Run suitecloud project:adddependencies
Run suitecloud project:deploy

### Actual Behavior
Receiving the below error:

```
Details: The following features must be specified in the manifest to use the STDBODYORDERSTATUS value with the Order Status condition builder parameter in the workflowtransition5 workflowtransition: SALESORDERS
Details: The following features must be specified in the manifest to use the -244 value with the Order Status1 condition builder parameter in the workflowtransition5 workflowtransition: ACCOUNTING
```

### Expected Behavior
Deploy of workflow should succeed

**Comment by colivares82** [comment]
Thanks for reporting @omrilit , we will take a look into it

**Comment by omrilit** [comment]
@colivares82  any updates on this one?

**Comment by omrilit** [comment]
@colivares82 any updates on this one?

**Comment by alii-gator** [comment]
@omrilit We are testing the fix, hopefully the fix will be included in the upcoming major release.

**Comment by omrilit** [comment]
Thanks for the update @alii-gator

**Comment by alii-gator** [comment]
@omrilit Can you please verify this in latest version `1.1.0`?

**Comment by omrilit** [comment]
The issue remained the same also in 1.1.0

**Comment by lfpvillegas** [comment]
Hi @omrilit .
We are currently reviewing still opened issues. I have been able to test it and deploy the file shared in this issue with current version without the need of adding STDBODYORDERSTATUS  to manifest.
Could you please check it out?
Thanks

**Comment by lfpvillegas** [comment]
I'm closing the issue because we have not been able to replicate it anymore and we have no received further info.
However, if you still experience the same problem. Please reopen it again.
Thanks.
