### ISSUE TITLE
Bundles Support In SDF

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#135]
In Netsuite documentation it's written that SDF Java CLI has an importbundle command (https://<ACCOUNT_ID>.app.netsuite.com/app/help/helpcenter.nl?fid=section_4788674233.html).
Is there any intention to support it also in SDF JS wrapper?

**Comment by colivares82** [comment]
Hello @omrilit, At the moment we have no plans to implement any bundle related enhancement, we will keep an eye on this request, but for the short term I would suggest that if you have that need, then use the SuiteCloud CLI for Java (as you mentioned)
