### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by AntondegSTX** [oracle/netsuite-suitecloud-sdk#138]
When doing a project:validate I am getting this error.
Internal error encountered (Null pointer exception).
[morgancargo.zip](https://github.com/oracle/netsuite-suitecloud-sdk/files/4758310/morgancargo.zip)

**Comment by AntondegSTX** [comment]
suitecloud --version = 1.0.4
Node -v = v13.10.1

**Comment by alii-gator** [comment]
@grugknuckle @AntondegSTX we have started looking in to the reported issue, thanks for the patience. We will update you ASAP.

**Comment by alii-gator** [comment]
@AntondegSTX just an update, we are already testing the fix for this unexpected behavior reported by you. Hopefully we will roll out the fix with upcoming major release.

**Comment by alii-gator** [comment]
@AntondegSTX 
@grugknuckle 
This is now fixed/available in latest version 
get the latest npm package version `1.1.0`
