### ISSUE TITLE
Standard Developer role has insufficient permissions

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#139]
### Your environment
**OS** : e.g. iOS Catalina 10.15.4
**Node.js version** : e.g. 14.14.4
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : iTerm2

### Describe the bug
When using the **Developer** role:
1. The _object:import_ command doesn't return workflow records.
2. The _file:import_ fails on `Details: Access denied. No extension allowed access.`

### To Reproduce
Follow the instructions under https://<ACCOUNT_ID>.app.netsuite.com/app/help/helpcenter.nl?fid=section_4724784139.html and use a token of a developer account.
1. Run suitecloud project:create -i (use ACCOUNTCUSTOMIZATION type)
2. Run suitecloud account:setup with the developer's token
3. run suitecloud object:import
3. run suitecloud file:import

**Comment by alii-gator** [comment]
@omrilit Unfortunately this is definitely not a problem with the tool itself. Please create an issue with Netsuite. We can't deal with this here.
Thanks for understanding.
