### ISSUE TITLE
Setup account fails for accounts with tstdrv prefix

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#140]
### Your environment
**OS** : e.g. iOS Catalina 10.15.4
**Node.js version** : e.g. 14.14.4
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : iTerm2

### Describe the bug
When trying to use account:setup for a developer account that starts with **tstdrv** it fails on:
`The token could not be validated. The authentication details are not valid or the server could not respond. Review your authentication details and try again.\nError details:\nInvalid login attempt.`

### To Reproduce
1. Enable all the required features for SDF as mentioned in https://<ACCOUNT_ID>.app.netsuite.com/app/help/helpcenter.nl?fid=section_4724921034.html&whence=
2. Setup your role for SDF development (for the Administrator role) https://<ACCOUNT_ID>.app.netsuite.com/app/help/helpcenter.nl?fid=subsect_1539287603.html
3. Create SDF ACCOUNTCUSTOMIZATIOM project.
4. Run suitecloud account:setup with the generated token id.

The same actions was done in a developer account that doesn't have the tstdrv prefix in its name and the bug did not appear.
The issue occurs also when working directly against the java CLI

**Comment by alii-gator** [comment]
@omrilit its a known behavior.
If you check your accountID it's in upper case. Like TSTDRV12345
So for now you have to use upper-case letters with your accountID.

We are planning on improving this in future releases, if a user provides lower case letters they will be converted to upper case automatically.

Try new with upper case letter and let us know if it works.

**Comment by omrilit** [comment]
@alii-gator thanks, it indeed works when using uppercase.
