### ISSUE TITLE
entryForm recordType value is inconsistent

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#156]
### Your environment
**OS** : iOS Catalina 10.15.4
**Node.js version** : 14.14.4
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : iTerm2

### Describe the bug
When importing a certain entryForm, there is inconsistency in the recordType value is has.
Sometimes **MARKUPITEM** is returned and sometimes **DISCOUNTITEM**.
[custform_11_2239021_974.txt](https://github.com/oracle/netsuite-suitecloud-sdk/files/4883114/custform_11_2239021_974.txt)
[custform_11_2239021_974 (1).txt](https://github.com/oracle/netsuite-suitecloud-sdk/files/4883133/custform_11_2239021_974.1.txt)

![image](https://user-images.githubusercontent.com/9881966/86733309-c3de0e00-c039-11ea-969b-50053846bfa8.png)

**Comment by alii-gator** [comment]
@omrilit This is not a problem related to the tool. It should be reported to netsuite custoemr support so they can forward it to relative team.

**Comment by omrilit** [comment]
@christopherwxyz I didn't ask NetSuite customer support but handled it in my application
