### ISSUE TITLE
Enhance the Error  Message for 'scloud deploy' when SDF is not enabled in the Account

### ISSUE THREAD

**Issue by naren2k6** [oracle/netsuite-suitecloud-sdk#16]
The Node.js CLI does give a meaningful error for the 'scloud setupaccount' command in case the user forgets to enable "Token Based Authentication" feature in the account. (which is good)

However, the Noce.js CLI does not give a meaningful error for the 'scloud deploy' command if the user has forgotten to enable the "SuiteCloud Development Feature" on his account.
The current error message says something like "Timed Out Exception"

**Comment by alii-gator** [comment]
Fix is available in master branch.
