### ISSUE TITLE
File Cabinet Folder Restriction

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#160]
Importing File Cabinet files is supported only from the following folders:
/Web Site Hosting Files/
/SuiteScripts/
/Templates/E-mail Templates/
/Templates/Marketing Templates/
(Taken from https://<ACCOUNT_ID>.app.netsuite.com/app/help/helpcenter.nl?fid=section_4724963992.html)

Is supporting importing files from all folders in your pipeline?
Many customers have vital files under other directories.
Thanks!

**Comment by alii-gator** [comment]
@omrilit This is a limitation from server side, If you think other FileCabinet folders should also accessible through tools for importing purpose, you should request a feature enhancement through Netsuite Customer support.

cc @colivares82 FYI
