### ISSUE TITLE
Error Message: The attribute "position" is invalid, no attributes are expected.

### ISSUE THREAD

**Issue by dspadea-9w** [oracle/netsuite-suitecloud-sdk#173]
### Your environment
**OS** : Macos Catalina
**Node.js version** : v14.5.0
**suitecloud-cli version** : 1.0.4
**Terminal/CMD tool** : iTerm2

### Describe the bug

Custom Entry Form extracted from account via object:import generates <fields> entry with `position="MIDDLE"` attribute that looks like:

```
<entryForm scriptid="custform_snip_id" standard="STDFORMATPROFILEFORM">
  <name>snip name</name>
  <recordType>FORMATPROFILE</recordType>
  <inactive>F</inactive>
  <preferred>F</preferred>
  <storedWithRecord>T</storedWithRecord>
  <mainFields>
    <defaultFieldGroup>
        <fields position="MIDDLE"> -->

```

This causes `project:validate` to produce the following error:

```
- Line No. 9 - Error Message: The attribute "position" is invalid, no attributes are expected.
```

### To Reproduce
1. Run suitecloud project:validate where one of your custom entry object .xmls has this attribute in the `<fields>` tag.

### Actual Behavior
Produces validation error: `Error Message: The attribute "position" is invalid, no attributes are expected.`

### Expected Behavior
Expected this validation to complete successfully.

### Additional context
Forms were designed via NetSuite UI and extracted via `suitecloud object:import`. They immediately fail validation without modification.

**Comment by alii-gator** [comment]
@dspadea-9w Thanks for reporting this. We will check the behavior.

**Comment by epelc** [comment]
Also just ran into this when trying to convert our customizations into an SDF project.

Notably the `suitecloud project:validate` command and `suitecloud project:deploy --dryrun` seem to run different conflicting validations. The validate command shows this position error while the deploy dryrun requires the position. The docs also specify a position field is available.

>Error Message: The attribute "position" is invalid, no attributes are expected.

https://github.com/oracle/netsuite-suitecloud-sdk/issues/312 seems to have related conflicting validation issues.

**Comment by ammpedro** [comment]
Hi,

Are there any updates on this? We are also encountering this in suitecloud 1.2.1 and Node v14.16.0. 

Thanks.

**Comment by alii-gator** [comment]
This issue is not with the tool itself, The issues with server side issues/validations etc have to be reported to Netsuite support.
This is not a problem with the CLI itself. Its the response coming from Netsuite SDF.

Please open a ticket with NS Support.
