### ISSUE TITLE
Error Message: Invalid "recordType" reference key "FORMATPROFILE"

### ISSUE THREAD

**Issue by dspadea-9w** [oracle/netsuite-suitecloud-sdk#174]
### Your environment

**OS** : Macos Catalina
**Node.js version** : v14.5.0
**suitecloud-cli version** : 1.0.4
**Terminal/CMD tool** :iTerm2

### Describe the bug
The following XML snippet was built using the NetSuite UI and extracted via `object:import`:

```
<entryForm scriptid="custform_snip_id" standard="STDFORMATPROFILEFORM">
  <name>snip_name</name>
  <recordType>FORMATPROFILE</recordType>
  <inactive>F</inactive>
  <preferred>F</preferred>
```

`project:validate` produces the following error message:

```
Line No. 3 - Error Message: Invalid "recordType" reference key "FORMATPROFILE".
```

### To Reproduce
1. Run suitecloud project:validate against a project containing  an Object xml for an entry form with record type FORMATPROFILE.

### Actual Behavior

Produces error:
```
Line No. 3 - Error Message: Invalid "recordType" reference key "FORMATPROFILE".
```

### Expected Behavior
Clean validation

### Additional context
This form was built using the NetSuite UI and extracted using the CLI's `object:import` method. It immediately fails validation without modification.

**Comment by alii-gator** [comment]
@dspadea-9w we will check this and get back to you with our investigation.

**Comment by alii-gator** [comment]
This issue is not with the tool itself, The issues with server side issues/validations etc have to be reported to Netsuite support.
This is not a problem with the CLI itself. Its the response coming from Netsuite SDF.

Please open a ticket with NS Support.
