### ISSUE TITLE
Feature Request: Add --skip-validation option to project:deploy

### ISSUE THREAD

**Issue by dspadea-9w** [oracle/netsuite-suitecloud-sdk#175]
We're in a bit of a bind where there seem to be validation issues on the project, even when the object XMLs were generated by the NetSuite UI and pulled right out of the account via `object:import`. We can't proceed with these errors, even though the XMLs are probably just fine. 

It'd be great if we could either skip validation, or override for a list of validation types and continue to use the CLI to deploy our app. I don't know if this takes the form of a big-hammer `--skip-validation` option to project:deploy, or if it looks a little more nuanced than that, but some way forward would really be helpful.

**Comment by alii-gator** [comment]
@dspadea-9w Thanks for bringing this up.
We will consider this enhancement request for non interactive mode. 
But you can already use this functionality in interactive mode. 
When you execute `suitecloud project:deploy -i` you can skip local validation.
Apart from that we know the problems with locall Validations and we are working with relevant teams to make that better.

**Comment by dspadea-9w** [comment]
Thank you @alii-gator! FYI, I tried it and still received validation errors, maybe from server-side validation?

```
 $ suitecloud project:deploy -i
 PASS  __tests__/sample-test.js
  Basic jest test with simple assert
    ✓ should assert strings are equal (2ms)
  Sample test with provided record module stubs
    ✓ should update Sales Order memo field (2ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.364s
Ran all test suites.
? Do you want to validate locally before deploying? No
Content protection was not applied because the hiding.xml and locking.xml files were not found in the "InstallationPreferences" folder of the project. You need to create both files in order to apply content protection.
To learn how to create a hiding.xml file, see https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1515950176.html.
To learn how to create a locking.xml file, see https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1543865613.html.
The deployment process has encountered an error.
2020-07-22 14:22:02 (PST) Installation started
Info -- Account [(PRODUCTION) 1 ? Dev Trailing]
Info -- Publisher ID [com.]
Info -- SuiteApp [com. (0.0.1)]
Info -- Framework Version [1.0]
Validate manifest -- Success
Validate deploy file -- Success
Validate objects -- Failed
Validate files -- Success
Validate folders -- Success
Validate translation imports -- Success
Validate preferences -- Success
Validate flags -- Success
*** ERROR ***

Validation failed.

An error occurred during custom object validation. (custform_snip_id)
Details: cvc-complex-type.2.3: Element 'fields' cannot have character [children], because the type's content type is element-only.
Details: The neverEmpty field is invalid or not supported.
File: ~/Objects/custform_snip_name.xml

2020-07-22 14:22:18 (PST) Installation FAILED (0 minutes 17 seconds)
```

**Comment by alii-gator** [comment]
@dspadea-9w this is server side validation.
You can never skip that. Even when you do local validations, server side validation is always performed. 
In this case the validation shown is not correct or we can say false positive. Which will be fixed soon in upcoming release. 
If you remove the neverEmpty tag, you will be able to pass this validation.

**Comment by alii-gator** [comment]
@dspadea-9w `suitecloud project:deploy` will now not do local validation unless `--validate` param is passed.
As is said serverside validation can never be skipped.
If you have need further help please open a new issue.

**Comment by dspadea-9w** [comment]
Thank you, @alii-gator!
