### ISSUE TITLE
Importing roles contains duplicate values which fail at validation time.

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-sdk#181]
### Your environment
**OS** : Ubuntu 18.04 (WSL)
**Node.js version** : 12.16.2
**suitecloud-cli version** : 1.0.2
**Terminal/CMD tool** : e.g. WSL in webstorm

### Describe the bug
Importing roles can result in duplicate elements in the XML file related to permissions which result in validation errors.

The following snippet from a role xml file imported with suitecloud:
```xml
 <permission>
      <permkey>[scriptid=customrecord_scm_dps_taskview]</permkey>
      <permlevel>FULL</permlevel>
    </permission>
    <permission>
      <permkey>[scriptid=customrecord_scm_dps_taskview]</permkey>
      <permlevel>FULL</permlevel>
      <restriction></restriction>
    </permission>
```
results in the following error when validation is run:

```
An error occurred during custom object validation. (customrole1071)
Details: Duplicate values [scriptid=customrecord_scm_dps_taskview] were found in the 'permissions' sublist on the 'role' record.
File: ~/Objects/customrole1071.xml
```

The error is occurring for any roles in my SDF project.

### Expected Behavior
Roles imported with SDF should never have duplicate elements?
Customizations imported by SDF tool should generally not fail validation by the same SDF tool.

**Comment by alii-gator** [comment]
@ShawnTalbert we will look in to this unexpected behavior. Taking a quick look this seems like an issue with server side and not with the tool itself.

**Comment by ShawnTalbert** [comment]
yes, note that I'm doing server-side validation for all these issues.

**Comment by alii-gator** [comment]
This issue is not with the tool itself, The issues with server side issues/validations etc have to be reported to Netsuite support.
This is not a problem with the CLI itself. Its the response coming from Netsuite SDF.

Please open a ticket with NS Support.
