### ISSUE TITLE
imported custom role can result in validation failure in the permissions section.

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-sdk#183]
### Your environment
**OS** : Ubuntu 18.04 WSL
**Node.js version** :  12.16.2
**suitecloud-cli version** : 1.0.4
**Terminal/CMD tool** : webstorm terminal WSL

### Describe the bug
Custom role XML created by importing using SDF results in failure when you turn around and validate project against same account.

imported role XML does include elements such as 
```xml
    <permission>
      <permkey>REPO_RECONCILE</permkey>
      <permlevel>EDIT</permlevel>
    </permission>
```

### To Reproduce
1. Import custom role with the permissions shown above or mentioned in error message below.
2. run suitecloud project:validate -i

### Actual Behavior
```
An error occurred during custom object validation. (customrole1040)
Details: Invalid permlevel reference key EDIT for permkey REPO_RECONCILE.
Details: Invalid permlevel reference key EDIT for permkey ADMI_ACCOUNTING.
File: ~/Objects/customrole1040.xml
```
### Expected Behavior
This should not result in an error since the imported custom role XML has not been modified.
Expectation is that any SDF imported role which is working in a NS account should validate successfully against same NS account.

**Comment by erikaschua** [comment]
Encountered similar error as well:
`An error occurred during custom object update.
Details: Invalid permlevel4 reference key 3 for permkey4 ADMI_ACCOUNTING.`

**Comment by cartylorenzo** [comment]
I hate to be that guy, but @erikaschua or @ShawnTalbert were either of you or your networks able to resolve this issue? Thank you in advance!

**Comment by alii-gator** [comment]
@ShawnTalbert 
This issue is not with the tool itself, The issues with server side validations etc have to be reported to Netsuite support.
This is not a problem with the CLI itself. Its the response coming from Netsuite SDF.

Please open a ticket with NS Support.

**Comment by PetOnion** [comment]
I have the same issue and I found that only NONE and FULL are allowed for ADMI_ACCOUNTING.

Permission Names and IDs
https://suiteanswers.custhelp.com/app/answers/detail/a_id/10521/

### Actual Behavior
```
<permission>
  <permkey>ADMI_ACCOUNTING</permkey>
  <permlevel>EDIT</permlevel>
</permission>
```

An error occurred during custom object update.
Details: Invalid permlevel4 reference key 3 for permkey4 ADMI_ACCOUNTING.
File: ~/Objects/customrole1018.xml
Object: customrole1018 (role)


### Solution
Change permission level to FULL.

```
<permission>
  <permkey>ADMI_ACCOUNTING</permkey>
  <permlevel>FULL</permlevel>
</permission>
```

Update object -- customrole1018 (role)
