### ISSUE TITLE
validation errors on permissions between roles and records.

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-sdk#184]
### Your environment
**OS** : Ubuntu 18.04 (WSL)
**Node.js version** : 12.16.2
**suitecloud-cli version** : 1.0.4
**Terminal/CMD tool** : webstorm WSL

### Describe the bug
I have unmodified custom records and custom role definitions imported into project.

It appears custom records don't contain the reference to custom roles? I'm seeing many errors similar to the following:

```
An error occurred during custom object validation. (customrole1031)
Details: The customrole1031 role contains a reference on the customrecord_sk_coo customrecordtype in the permkey field but the customrecordtype does not reference the role. You must
 either reference the role from the customrecord_sk_coo customrecordtype object or remove the permission from the customrole1031 role.
```

### To Reproduce
1. Import custom record and custom role that has permissions on custom record
2.  Run suitecloud project:validate -i

### Expected Behavior
Validation errors should not happen on freshly imported custom role and custom record (the imported XML should properly include references to each other as needed if this validation error is legitimate).

**Comment by ShawnTalbert** [comment]
Also, as a workaround, how exactly do I manually edit the *custom record* XML to properly reference the *custom role*?

I think that's the missing/broken piece, and would prefer to do that rather than remove the permission from the role altogether.

**Comment by ShawnTalbert** [comment]
one thought - could this be an issue with **inactive** roles? A role can be marked inactive and apparently still appear on the permissions list for a custom record in the UI.... but does SDF simply not pull down/generate XML for inactive roles when creating the custom record definition XML?

**Comment by alii-gator** [comment]
@ShawnTalbert We have made some improvements in local validations but still there are some pending issues, please try the same in newer version **early next week** and let us know if you experience the same problem.
Will update you when we release the newer version. I will keep this issue open so you can give your feedback

**Comment by alii-gator** [comment]
@ShawnTalbert Can you please verify this in newest tools version. As i said in my previous comments, If this is not fixed please open a Case with NetSuite Tech Support.

**Comment by ShawnTalbert** [comment]
I actually can't verify this as I'm not working with that project any more (I think we gave up on using SDF for that one).

I'm not sure NetSuite support would have a clue on an error like this but if this is a way to get it resolved I'll do that if I see it again. Thanks @alii-gator

**Comment by irurzo** [comment]
Same issue here, 

`An error occurred during custom object validation. (customrole_cfo)
Details: The customrole_cfo role contains a reference on the customrecord_encounter customrecordtype in the permkey field but the customrecordtype does not reference the role. You must either reference the role from the customrecord_bit_encounter customrecordtype object or remove the permission from the customrole_cfo role.`

Then if I add the role on the custom record, I get a circular error 

`Details: Circular dependencies detected. The following custom objects reference each other in a way that creates direct dependencies: customrecord_encounter -> customrole_cfo -> customrecord_encounter`

Now if we remove it from the role and only set it on the custom record, I get the first error

`The customrecord_encounter customrecordtype contains a reference on the customrole_cfo role in the permittedrole field but the role does not reference the customrecordtype. You must either reference the customrecordtype from the customrole_bit_cfo role object or remove the permission from the customrecord_encounter customrecordtype.`
