### ISSUE TITLE
Error on `npm install -g @oracle/suitecloud-cli`

### ISSUE THREAD

**Issue by cja-github** [oracle/netsuite-suitecloud-sdk#185]
### Your environment
**OS** : Windows 10
**Node.js version** : 14.7.0
**suitecloud-cli version** : Not installed
**Terminal/CMD tool** : cmd.exe

### Describe the bug
I ran `npm install -g @oracle/suitecloud-cli` and it errored. See attached log.

### To Reproduce
1. Run `npm install -g @oracle/suitecloud-cli`
[2020-08-06T16_58_38_302Z-debug.log](https://github.com/oracle/netsuite-suitecloud-sdk/files/5040603/2020-08-06T16_58_38_302Z-debug.log)

**Comment by alii-gator** [comment]
@cja-github This problem might be fixed with some changes we have made in upcoming release.
Please try to install the newer version and give your feedback if you still face the same issue.
The newer version will be available around early next week.

**Comment by alii-gator** [comment]
@cja-github Can you install the latest version `1.1.0` and check if you encounter same issue?
If Yes, please do share logs.

**Comment by alii-gator** [comment]
Closing this issue since there is no response. If you still encounter same or new problems please open the issue again.
