### ISSUE TITLE
An error occurred during custom object creation/update

### ISSUE THREAD

**Issue by webdevelopersdiary** [oracle/netsuite-suitecloud-sdk#188]
### Your environment
**OS** : Ubuntu 18.04.4 LTS
**Node.js version** : v12.18.3 LTS
**suitecloud-cli version** : 1.0.4
**Terminal/CMD tool** : Gnome Terminal

### Describe the bug
When deploying a SuiteApp with transaction body fields (or custom record fields) that have a formula as a default value which contains a CASE expression, then `suitecloud project:deploy` fails with an error, even though validation passes locally and with the target account and the actual fields work normally without error in NetSuite when manually created by hand using the point-and-click builder in the user interface. This seems to be a problem on the server side during the deployment of a SuiteApp.

### To Reproduce
* Checkout this git repository: https://github.com/webdevelopersdiary/suitecloud-sdk-formula-bug
* Open a command line terminal and change directory to `./com.fastfour.suitecloudsdkformulabug/`.
* Run `npm install`
* Run `suitecloud account:setup -i` to point SuiteCloud CLI to a NetSuite account to which you have access.
* Run `npm test` to make sure the project is able to validate locally and against the target account. This command should succeed okay.
* Run `npm run deploy` to trigger the error.

### Actual Behavior
```
> suitecloud project:deploy --validate

The deployment process has encountered an error.
2020-08-14 05:39:26 (PST) Installation started
Info -- Account [(PRODUCTION) SDF Testing Account #2]
Info -- Publisher ID [com.fastfour]
Info -- SuiteApp [com.fastfour.suitecloudsdkformulabug (1.0.0)]
Info -- Framework Version [1.0]
Validate manifest -- Success
Validate deploy file -- Success
Validate objects -- Success
Validate files -- Success
Validate folders -- Success
Validate translation imports -- Success
Validate preferences -- Success
Validate flags -- Success
Validate account settings -- Success
Validate Custom Objects against the Account -- Success
Validate file cabinet items against the account -- Success
Validate translation imports against the account -- Success
Info -- Current installed version [1.0.0]
Begin deployment -- com.fastfour.suitecloudsdkformulabug (1.0.0)
Create folder -- ~/FileCabinet/SuiteApps/com.fastfour.suitecloudsdkformulabug/
Upload file -- ~/FileCabinet/SuiteApps/com.fastfour.suitecloudsdkformulabug/test.txt
Update object -- custbody_ff_example_formula (transactionbodycustomfield)
*** ERROR ***

An error occurred during custom object update.
File: ~/Objects/custbody_ff_example_formula.xml
Object: custbody_ff_example_formula (transactionbodycustomfield)
2020-08-14 05:39:27 (PST) Installation FAILED (0 minutes 1 second)
```

![Field details](https://raw.githubusercontent.com/webdevelopersdiary/suitecloud-sdk-formula-bug/master/custbody_field.png)

### Expected Behavior
The expected behavior is that it should be possible to deploy fields that have a CASE formula as its default value, especially since these have been created in the NetSuite user interface, then imported using SuiteCloud CLI, but then can not be deployed again using SuiteCloud CLI. Running `suitecloud project:deploy` should succeed without any errors.

### Additional context
Please also see the README.md in this repository for additional information, screenshots and a ready example which can instantly reproduce this error: https://github.com/webdevelopersdiary/suitecloud-sdk-formula-bug

**Comment by alii-gator** [comment]
@webdevelopersdiary 
This doesn't seem like a problem with the tool.
Please open an issue with netsuite technical support.

**Comment by dpurtschert** [comment]
I am experiencing the same issue with a custom object using html (input type button with onclick javascript) as the default value. Anyone have any ideas on how to resolve it?

**Comment by veronicacbs** [comment]
Hi @dpurtschert, 
After reviewing on our side, it appears this issue is not related to the tool. We recommend opening an issue with NetSuite Technical Support for further assistance.
