### ISSUE TITLE
Emit the accountid being used

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-sdk#20]
For those (many) of us that work with multiple netsuite accounts, it would be great if the output of commands clearly indicated which account was being used.

e.g. output "NetSuite Account: 123456789_SB1" or similar as a clear (colorized?) part of the output so we know which account we're about to update/read from.

**Comment by margabit** [comment]
This is a great suggestion. I think @colivares82 already has a story to improve command output in the backlog. 

Tagging this issue as `enhancement` and leaving it open until it is revolved.

**Comment by alii-gator** [comment]
@ShawnTalbert 
This is now fixed/available in latest version 
get the latest npm package version `1.1.0`
