### ISSUE TITLE
How do I extends standard modules or modify properties?

### ISSUE THREAD

**Issue by fage789** [oracle/netsuite-suitecloud-sdk#211]
'util.extend' can only help me extends custom objects or modify custom object properties.
That's my way, but I don't think it's good.

```
let form = ServerWidgetModule.createForm({
		title: 'test'
	});
```
`// Add custom properties`
```
Object.assign(form.constructor, {
	addFields(arg1, arg2) {
		···
	},
})
```
```
form.addFields();
```

**Comment by vic-nik** [comment]
Hello @fage789 ,
Thanks for your question. This is the place to report netsuite-suitecloud-sdk related issues, for the general SuiteScript API related questions I suggest you use other channels like SuiteAnswers, specialized Slack channels, StackOverflow etc. I would also advise going through NetSuite Help Center documentation.
