### ISSUE TITLE
Fails to install on MacOS Catalina

### ISSUE THREAD

**Issue by yuri-urban** [oracle/netsuite-suitecloud-sdk#232]
### Your environment
**OS** : MacOS Catalina 10.15.6
**Node.js version** : 14.11.0
**suitecloud-cli version** : 1.1.1
**Terminal/CMD tool** : MacOS built-in Terminal app

### Describe the bug
After cloning the repo from github, changing into dir and running npm install, I get the errors listed below. Also MacOS GUI pop-up comes up saying: "The xcodebuild command requires the command line developer tools. Would you like to install the tools now?". So when I hit "Install" button the licence agreement comes up which I "Agree", and then "Finding software" screen progress goes on for a sec and then the message pops up saying "Can't install the software because it is not currently available from the Software Update server". Also, the described solution from https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d webpage does not work for me either, I end up with the same error message.

So here is the error log:

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/admin/netsuite-suitecloud-node-cli/extensions/localserver-cli-command/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.11.0/bin/node" "/Users/admin/netsuite-suitecloud-node-cli/extensions/localserver-cli-command/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/admin/netsuite-suitecloud-node-cli/extensions/localserver-cli-command/node_modules/node-sass
gyp ERR! node -v v14.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-09-24T11_14_31_495Z-debug.log

lerna ERR! npm install exited 1 in '@oracle/suitecloud-cli-localserver-command'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @oracle/suitecloud-sdk@1.1.1 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @oracle/suitecloud-sdk@1.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-09-24T11_14_31_549Z-debug.log

### To Reproduce
1. git clone the repo
2. cd into the cloned repo dir
3. npm install

**Comment by alii-gator** [comment]
@yuri-urban Mac OS requires you to install/enable xcode for development purposes i most of the cases.
Have them installed before hand and then try to install suitecloud cli.
It seems like a problem with your dev environment and not with CLI it self.

**Comment by yuri-urban** [comment]
> @yuri-urban Mac OS requires you to install/enable xcode for development purposes i most of the cases.
> Have them installed before hand and then try to install suitecloud cli.
> It seems like a problem with your dev environment and not with CLI it self.

@alii-gator i know it's the problem with OS, and this is exactly what i have highlighted. MacOS Catalina does not find the necessary xcode component in its OS updates with the error I have stated in the body of my original message. This means that SuiteCloud CLI tool is not Catalina-compatible at the moment.

**Comment by alii-gator** [comment]
@yuri-urban Can you try executing this and tell me the output
`xcode-select -p`

**Comment by yuri-urban** [comment]
@alii-gator there you go:

macbook-pro-15:~ admin$ sudo xcode-select -p
Password:
xcode-select: error: unable to get active developer directory, use `sudo xcode-select --switch path/to/Xcode.app` to set one (or see `man xcode-select`)

**Comment by vic-nik** [comment]
If you would like to run node-cli in development mode (as opposed to installing from npmjs.com) the steps should be:

1. git clone https://github.com/oracle/netsuite-suitecloud-sdk.git
2. cd netsuite-suitecloud-sdk/packages/node-cli
3. npm install
4. npm link (optional, if you would like "suitecloud" command to be globally available in your system)

Note that you have to run "npm install" from node-cli directory and not from the root of the project. It may not solve the xcode problem which seems to be specific to your environment but it's the right sequence of steps.

**Comment by yuri-urban** [comment]
@vic-nik I have already tried this exact sequence of steps. It does not help, because it fails with the xcode part. Catalina fails to install the missing components of the xcode saying "Can't install the software because it is not currently available from the Software Update server".

What is my next step to resolve this?

**Comment by vic-nik** [comment]
We would need to reproduce that in Catalina. Does installation from npmjs.com work for you (npm install -g @oracle/suitecloud-cli)?

**Comment by yuri-urban** [comment]
@vic-nik just tried it. Ends up with exact same results, errors as in my original message and then a pop-up asking to install xcode command line tools, where i click "Install" -> "Agree" and then get the same error message saying "Can't install the software because it is not currently available from the Software Update server"

**Comment by vic-nik** [comment]
Ok, thanks for feedback. We will try to reproduce that in Catalina and will provide more info here.

**Comment by yuri-urban** [comment]
@vic-nik thank you Victor. FYI - I have just also done today's fresh OS update on Catalina and re-ran the 'npm install', but still ran into exact same issues.

**Comment by alii-gator** [comment]
@yuri-urban @vic-nik I tried on 
OS : MacOS Catalina 10.15.6
I was able to install without any issue.
So you should be able to install xcode command line tools. Try installing from app store.
If you haven't already try this [article](https://apple.stackexchange.com/questions/337744/installing-xcode-command-line-tools) please.

**Comment by vic-nik** [comment]
Thanks for checking that Ali. I tend to think it's environment problem too as no one else has reported similar issues on Catalina so far.

**Comment by yuri-urban** [comment]
@alii-gator and @vic-nik thanks for your help guys, I did try installing it from the App Store... it took about an hour, but after finishing the install, starting up Xcode and letting it "update components" - the npm install went successful. Therefore this issue can be closed now.
