### ISSUE TITLE
Zsh: command not found: suitecloud

### ISSUE THREAD

**Issue by Ulvenas** [oracle/netsuite-suitecloud-sdk#233]
### Your environment
**OS** : iOS Catalina 10.15.6 
**Node.js version**  v12.18.3
**suitecloud-cli version** : Run `suitecloud --version` to check the version
**Terminal/CMD tool** : mac OS Terminal

### Describe the bug
After having successfuly installed suitecloud with 'npm install -g @oracle/suitecloud-cli', I receive: command not found error when typing  'suitecloud'.

### To Reproduce
1. install suitecloud with npm install -g @oracle/suitecloud-cli
2. Run 'suitecloud' in the terminal 

### Actual Behavior
![suitecloud](https://user-images.githubusercontent.com/28529291/94434252-c3b56080-0199-11eb-830d-c80e426ab727.png)

### Expected Behavior
I should receive a list of suitecloud commands by typing 'suitecloud' in the terminal after installation. 

### Additional context
I have tried installing suitecloud in a separate folder without success.

**Comment by alii-gator** [comment]
@Ulvenas This looks weird. The installation seems to be successful.
Restarting the terminal after installation also doesn't help?
My first guess is that it's a problem with your npm installation.
your global packages are not recognized properly.

Check this [article](https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59) if it helps.

**Comment by Ulvenas** [comment]
Thank you @alii-gator! 
I followed the instructions from the article and now it works fine 👍
