### ISSUE TITLE
Recommendation for java heap space parameters

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#236]
Is there any recommended -Xms & -Xmx values I should set when running SDF?

**Comment by vic-nik** [comment]
Hi Omri,
We don't have recommendation and assume that default values should work for common development tasks.
I would only consider changing them if your workflow is really demanding (like running resource intensive commands in automated environment) and if you end up with OutOfMemoryError. It's hard to recommend specific value without knowing exact use case and resources available. These numbers should ideally be determined by profiling the application in specific environment.
