### ISSUE TITLE
Replace request-promise-native

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#239]
There are 2 main issues with the request-promise-native package:
1. As described [here](https://www.npmjs.com/package/request-promise-native) it's deprecated which means that there are no security patches added to it.
2. There is a problem using this package in jest as described [here](https://github.com/request/request-promise/issues/247).

Would appreciate if you could replace this package, thanks!

**Comment by alii-gator** [comment]
@omrilit Thanks for bringing this up. We will check this.

**Comment by alii-gator** [comment]
Tracked Internally - 3774

**Comment by alii-gator** [comment]
Should be fixed in newer version `1.3.0`
