### ISSUE TITLE
should stubs be `jest.fn()` rather than empty functions?

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-sdk#241]
**suitecloud-cli version** : 1.1.1

### Describe the feature
I've only just glanced at the unit testing support (looking at the http stubs) and it appears we've chosen to use empty functions as the 'stubs' in most cases. 

Wondering if we'd be better served by having stubbed functions be `jest.fn()` instead of plain empty functions, so that we can interrogate how/if the stubs were called during a test? It's definitely still evolving but has proven useful for NFT. 

Here's a simple example of what I mean, mocking `getRemainingUsage()`:

* the mock for [getRemainingUsage](https://github.com/ExploreConsulting/netsuite-fasttrack-toolkit-ss2/blob/master/__mocks__/N/runtime.ts) 

* and [some unit tests](https://github.com/ExploreConsulting/netsuite-fasttrack-toolkit-ss2/blob/master/test/governance.test.ts) that leverage that rich jest mock.

**Comment by ShawnTalbert** [comment]
Wait, I see now in the example you're mocking the entire module ( e.g. `jest.mock('N/record')`). I guess that indirectly achieves the same result, as long as the caller remembers to call `jest.mock`.

I don't remember for sure but I seem to recall some issues with jest.mock() - maybe you lose the friendly string function names in error output?

**Comment by vic-nik** [comment]
Hi Shawn, 
Thank you for your feedback and suggestion.
You are right, we provide stubs for entire module and you can mock behaviour for individual functions as needed. Not sure about downsides of using jest.mock(), we haven't seen any related concerns so far but please let us know if you find any issues with that approach.

**Comment by alii-gator** [comment]
@ShawnTalbert Closing this issue, please feel free to add comments or open new issue if you need help with something.
