### ISSUE TITLE
WebStorm SuiteCloud IDE import objects and Java sdfcli listobjects treat underscore as wildcard

### ISSUE THREAD

**Issue by zachvictor** [oracle/netsuite-suitecloud-sdk#276]
### Your environment
**OS** : Windows 10
**Node.js version** : 12.14.0
**suitecloud-cli version** : 1.1.2
**Terminal/CMD tool** : PowerShell or cmd / WebStorm 2020.3 + SuiteCloud IDE 2020.2.0

### Describe the bug
When the scriptid parameter allows for partial-matches, as in Java CLI `sdfcli listobjects` and the SuiteCloud IDE import objects functionality, the underscore character (`_`) is treated as a single-character wildcard. 

### To Reproduce
1. In Java `sdfcli`, execute a properly formed `listobjects` call passing an argument containing a literal underscore for the -scriptid param. 
2. Alternatively, in the SuiteCloud IDE, follow the steps to import objects. Filter by scriptid using a partial string that contains an underscore. 

### Actual Behavior
The sdfcli / IDE treats underscore as a wildcard character. Any character in that position is considered a match.

### Expected Behavior
The underscore is matched literally. This would fit well with the practice recommended by Oracle-NetSuite and widely adopted, because it would enable exact matches that contain the underscore character. Also, it would correct the undocumented and potentially problematic behavior of underscore-as-wildcard. 

#### Exact matches matter for NetSuite standard/leading practices for scriptid definition
Treating underscore as wildcard is problematic, because NetSuite's recommended practice for scriptid values is to begin the scriptid with an underscore. See _SuiteScript Developer Guide 2020.2_, p. 35, Section "SuiteScript Best Practices," Subsection "General Development Guidelines," bullet point 3: "Prefix all custom script IDs and deployment IDs with an underscore (`_`)." This practice is recommended by Oracle-NetSuite and is widely adopted. The problem with the behavior of the underscore-as-wildcard is that it makes it impossible to specify an exact match for scriptid values that contain an underscore. For example, if my company is _Foo, Inc._ and I use `_foo_` as the prefix to begin the user-controlled part of scriptid values, then `sdfcli listobjects` or SuiteCloud IDE import objects filtering will return (for example) customrecord_foo_myrec, customrecord_abc_foodstuff, customrecord_xyz_123_foolishness, etc. 

#### Use cases
Not being able to match a scriptid exactly is not a big deal if one is searching for a relatively small number of objects. It becomes a problem when you need to retrieve a list of all objects matching a partial scriptid. The "all matches" scenario is common when you want to grab script IDs prefixed with an org-designating string: for example, all custom objects created by ACME, Inc. might have _acme_ as the prefix of the user-defined portion of the scriptid.

The "get-all matching" use case is relevant to at least three common development scenarios:
1. Change objects that are part of an existing body of work with interdependencies.
2. Bring an existing body of work into version control.
3. Identify objects that are distinctly part of an existing body of work as distinct from other customizations brought in via bundles, SuiteApps, and the like. 
In these three general use cases, the "existing body of work" can be identified by matching on a part of the scriptid, usually the first part beginning with the underscore--that's why exact (not wildcard) match on underscore becomes so important.

#### Possible root cause
If the input processed by sdfcli and SuiteCloud IDE is ultimately used to form a database query, it is likely that the literal `_` is interpreted by the database as a wildcard.

In both Oracle SQL and ANSI SQL, the `LIKE` operator is used for rudimentary pattern-matching based on partial string values. The standard wildcard characters are `_` and `%`. The `LIKE` operator features an optional `ESCAPE` clause, which allows one to specifiy an "escape character": that is, a character that can be prepended to an underscore or percent sign to designate their respective literal values. Examples:
```sql
-- 1. Hypothetical backend DB query showing how an underscore in literal input is interpreted as a wildcard
SELECT scriptid FROM custom_objects WHERE scriptid LIKE '%_foo_%';

-- 2. Hypothetical backend DB query showing how an underscore in parameterized input is interpreted as a wildcard
-- In this example, the input '_foo_' is bound to variable :sdfcli_scriptid_input
SELECT scriptid FROM custom_objects WHERE scriptid LIKE '%' || :sdfcli_scriptid_input || '%';

-- 3. Hypothetical backend DB query showing literal input "escaped" so that _ is interpreted literally
SELECT scriptid FROM custom_objects WHERE scriptid LIKE '%\_foo\_%' ESCAPE '\';

-- 4. Hypothetical backend DB query showing one solution to escape underscore in user input functionally
-- REPLACE transforms literal _ to \_
-- LIKE with ESCAPE treats the character that follows \ as literal (not wildcard)
SELECT scriptid FROM custom_objects WHERE scriptid LIKE '%' || REPLACE(:sdfcli_scriptid_input, '_', '\_') || '%' ESCAPE '\';
```
I prepared an example using Oracle Live SQL that may be easier to observe and understand:
https://livesql.oracle.com/apex/f?p=590:43:22892594932912:::43:P43_ID:242010414865622977615914799594589565034
I took a screenshot of the two queries and result sets that demonstrate the behavior (attached).
![underscore-wildcard-literal-in-sql](https://user-images.githubusercontent.com/299594/101706400-d53ea280-3a3d-11eb-9f49-0217d89867b2.png)

#### Final notes
Thank you for your continuing work on the CLI and IDE tools. They are remarkably good--save time, bring clarity to development and customization, accelerate the time-to-delivery, integrate increasingly well with mature SDLC processes.

**Comment by alii-gator** [comment]
@zachvictor Thanks for the detailed description of the issue. We will check it and get back to you with updates.

**Comment by zachvictor** [comment]
@alii-gator Thanks you. I updated the description to include a possible root cause. It seems likely that the issue originates at the database layer, because SQL interprets `_` as a wildcard.

**Comment by alii-gator** [comment]
@zachvictor can you still replicate this issue in latest tools?

**Comment by zachvictor** [comment]
Hello, @alii-gator ! I will try to replicate. 

Do you know if it was addressed in the latest release?

**Comment by zachvictor** [comment]
@alii-gator The issue remains as it was. Please re-open. The attached video is a brief demo illustrating the exactly of "_foo_" (above). If underscore were interpreted as a string literal, then "_foo_" would match one and only one of the three customrecordtypes that I created in this dev account for this test. If underscore were interpreted as a single-character wildcard, then "_foo_" matches all three.

Related issue, not discussed above: the SuiteCloud IDE script ID search filter is a  "contains" filter: it's the equivalent of putting the 0 or more wildcard character at the beginning and end of the parameterized value. In consequence, given an environment that has both (for example) `customrecord_red_ball` and `customrecord_red_balloon` one has no way to pinpointing "red ball"—not even if one spells out the ID in entirety. The implict `%`s transform the filter value from `customrecord_red_ball` to `customrecord_red_bialloon`; since the shorter one is an exact subset of the longer, any search filter that can match the shorter will always yield the latter too. So, in addition to consideration of underscore-as-wildcard, it would be appropriate to re-consider the decision to auto-wrap scriptid search criterea in a 0-or-more characters wildcard (%)

**Comment by zachvictor** [comment]
Any word on this one? I understand it's closed; still, I figured it wouldn't hurt to ask.
