### ISSUE TITLE
jest startup performance

### ISSUE THREAD

**Issue by dylbarne** [oracle/netsuite-suitecloud-sdk#292]
### Your environment
**OS** : Windows 10
**Node.js version** : v14.15.4
**suitecloud-cli version** : 1.1.2
**Terminal/CMD tool** : VSCodeTerminal

### Describe the bug
running simple included jest test is quite slow, takes ~2.5-3 seconds (seems mainly just to startup of jest/runner itself, however the actual test execution is performed very quickly)
Started looking further into jest docs & issue, seems similar to described here: https://github.com/facebook/jest/issues/7963
Seems adding Jest Config option of **testEnvironment** change to 'node' improves performance by ~1.5 seconds

### To Reproduce
1. Use `suitecloud project:create` command to create new SDF Project
2. Run `npm run test` to execute jest tests, in context of SDF Project
2. Observe slow performance
3. Add `testEnvironment : 'node'` to exports of jest.config.js https://jestjs.io/docs/en/configuration#testenvironment-string
4. Observe that performance increases

### Actual Behavior
Performance is slow due to default testEnvironment including jsdom components, which should not be needed for SuiteScript testing? There may be other CLI or Config flags to also boost performance _(admittedly I am not familiar with jest unit testing much at all, the testEnvironment just seemed like a simple one to verify)_

### Expected Behavior
Any Config or CLI options that are relevant for SuiteScript Unit Testing would ideally be included in this suitecloud unit-testing package (either coming from `SuiteCloudJestConfiguration.build()` automatically, or perhaps even just a suggestion in Unit Testing README of relevant additional flags to be added.

**Comment by alii-gator** [comment]
@dylbarne Thanks for the suggestions, we will investigate it further and will keep you updated. Thanks

**Comment by dylbarne** [comment]
I believe this can be closed, since as of Jest v27 now default testEnvironment is node
https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults
