### ISSUE TITLE
Referencing of parentsubtab results in an error when deploying objects concurrently.

### ISSUE THREAD

**Issue by nrdejesus** [oracle/netsuite-suitecloud-sdk#295]
### Your environment
**OS** : Windows 10 x64
**Node.js version** : 12.18.2
**suitecloud-cli version** : 1.1.2
**Terminal/CMD tool** : Git Bash

### Describe the bug
This issue occurs when objects that have dependencies on each other are concurrently deployed to a single account.
Details: Invalid parentsubtab reference key <customRecordId> for selectrecordtype <customRecordId>.

### To Reproduce
1. Create XML definitions for both objects
2. Deploy both objects to a NetSuite Account (execute CLI command suitecloud project:deploy)

### Actual Behavior
Sample Code/s
- Parent Record XML
![image](https://user-images.githubusercontent.com/55890045/106847107-3ce53700-66e9-11eb-9228-d75b670f1d2c.png)

- Child Record XML
![image](https://user-images.githubusercontent.com/55890045/106847115-3fe02780-66e9-11eb-9dee-c5e80dd5292b.png)

- Deploy XML
![image](https://user-images.githubusercontent.com/55890045/106847122-440c4500-66e9-11eb-8e95-6b71b39124f2.png)

Deployment proceeds until it encounters the said object/s.
**Actual Error message:**
![image](https://user-images.githubusercontent.com/55890045/106846583-2094ca80-66e8-11eb-97fe-8d4fe385ce6a.png)

### Expected Behavior
The deployment should proceed since scriptid references are correct.

### Additional context
- Both objects are yet to be created to an account.
- A similar error seems to occur when deploying records that contains a field that points to itself.

**Comment by alii-gator** [comment]
@nrdejesus We will take a look at it and if its the issue with the tool we will fix it and if (most likely) it's a problem on server side you will have to create a netsuite issue via customer support.

**Comment by alii-gator** [comment]
@nrdejesus I discussed this with my team, and we think we will need to involve some other teams.
For that reason please contact NS Support and advise them to assign this to "Platform Suitecloud Development" Team and we will take care of that there.

With that i am closing this issue here.

**Comment by nrdejesus** [comment]
Hi @alii-gator ,

Thanks! I'll update this thread with the case # for your reference.

**Comment by bernsteinmatt1717** [comment]
Was there ever an update? I've run into the same issue
