### ISSUE TITLE
Package SuiteApp to Zip fails when custom forms are included

### ISSUE THREAD

**Issue by MrRob** [oracle/netsuite-suitecloud-sdk#312]
### Your environment
**OS** : MacOS 11.2.2 (Big Sur)
**Node.js version** : e.g. 14.16.0
**suitecloud-cli version** : 1.1.2
**Terminal/CMD tool** : Mac Terminal app (zch)

### Describe the bug
When I try to run suitecloud project:package on a SuiteApp that contains custom forms, it tries to validate the project, and I get many warnings and errors that don't come up during normal validation (the warnings and errors shown seem incorrect).  A few examples (from validating a custom form) are:
 - Line No. 1 - Error Message: The attribute "standard" has an invalid value.
 - Line No. 13 - Error Message: The attribute "position" is invalid, no attributes are expected.
 - Line No. 8 - Error Message: The attribute "scriptid" is invalid, no attributes are expected.

### To Reproduce
1. Run suitecloud project:package on a SuiteApp that contains at least one custom form object

### Actual Behavior
Incorrect warnings and errors are generated, see attached screenshot
<img width="1327" alt="Screen Shot 2021-02-27 at 6 33 49 AM" src="https://user-images.githubusercontent.com/448678/109378121-e58d4d80-78c7-11eb-836b-44427c001c53.png">

### Expected Behavior
No validation should run - a zip file should be generated.

### Additional context
I prefer to use WebStorm, which is where I first found this problem.  The workaround is to use Eclipse instead, which is quite painful.

**Comment by alii-gator** [comment]
@MrRob We will investigate this and will update you as soon as possible.
But the validation is necessary because this package of suiteapp is supposed to be for MarketPlace. So we need to make sure that its ready and there are no validation errors.

**Comment by MrRob** [comment]
@alii-gator Sure, that's fair.  I suppose the expectation is then that it runs the same validation as the normal validate command.  It seems to be running a different validation process.  Thank you!!

**Comment by ammpedro** [comment]
Hi, 

Are there any updates on this? We are also encountering this in suitecloud 1.2.1 and it will potentially block automation. 

An observation though, is that the warnings are overriden by using the `suitecloud project:package -i` which generates a zip file under the build folder. 

Thanks.

**Comment by MrRob** [comment]
@ammpedro I'm still having this problem as well.  And using the -i flag doesn't solve it because I still have the error about the WMSSYSTEM missing from the manifest (which is a separate bug).  Sadly I'm still using Eclipse as the workaround.

**Comment by ammpedro** [comment]
Hi @MrRob, Ah! Yes you are right, only when `<feature required="true">WMSSYSTEM</feature>` is in the manifest, that `suitecloud project:package` is successful. We have also resorted to using Eclipse as the workaround, but the SuiteCloud IDE for Eclipse will be deprecated in 22.1. 
I've been back and forth with NS Support and they are still providing Eclipse as a workaround as well, but it defeats the purpose of the CLI. They have defect #605794 for the WMSSYSTEM error; it's currently a U6, bumped up from a U7...

**Comment by alii-gator** [comment]
@MrRob This will be fixed in upcoming release.
Since there are some issues with local validation. We are going to remove local validation step while packaging.

So a user should be responsible to validate locally/server side before packaging.

**Comment by MrRob** [comment]
@alii-gator I appreciate the update!  It seems that the good news is that the 2021.1 WebStorm plugin is now able to successfully generate the project zip files, which is amazing progress.  I still get the error in the CLI, but at least with it working in WebStorm we don't have to use Eclipse anymore. Thank you!

**Comment by alii-gator** [comment]
@MrRob We have removed Flaky Local validation in newest version `1.3.0`.
you can manually validate against server and package if all is validated correctly.
The package command will not run validation.

Run `npm install -g @oracle/suitecloud-cli`
