### ISSUE TITLE
Saved searched scriptid ending in number uploads as different scriptid then fails deploy on second update

### ISSUE THREAD

**Issue by epelc** [oracle/netsuite-suitecloud-sdk#362]
### Your environment
**OS**  macOS 11.3.1 
**Node.js version** :  14.17.0
**suitecloud-cli version** : 1.2.1
**Terminal/CMD tool** :  macOS Terminal
### Describe the bug

If you use a scriptid ending in a number for a saved search(potentially other types too?) and deploy it via the cli it will end up in netsuite as `customsearch_myid_2_2` instead of `customsearch_myid_2`. Because of this if you try to deploy again via `suitecloud project:deploy` you get an error because the search has the same name as another search yet it's trying to upload as `customsearch_myid_2` while there is already a `customsearch_myid_2_2` in the system.

### To Reproduce

- Create a custom search with a scripid ending in a number
- Deploy it
- It should work the first time if that custom search is not in your account
- It will upload but the scriptid changes to append a `_2` after oyur number ie `customsearch_myid_2` becomes `customsearch_myid_2_2`
- This different id causes an error on the next upload because there is a name conflict and you are trying to upload a different id instead of update an exisitng one now.

I believe netsuite's backend may be changing the scriptid on upload. Please fix this so you can use numbers or document/error out with an error that you aren't allowed to use them as suffixes.

**Comment by lfpvillegas** [comment]
Hi @epelc . I have been investigating and couldn't replicate the behavior.
It may have been solved.
Anyway, if this continue to happen, please fill a ticket to Customer Support. This validation and renaming is not made in this tool but in NetSuite internal process.

Thanks
