### ISSUE TITLE
suitecloud project:deploy. error  - com.sun.net.ssl.internal.ssl.Provider

### ISSUE THREAD

**Issue by dturton** [oracle/netsuite-suitecloud-sdk#363]
### Your environment
**OS** : BigSur 11.3
**Node.js version** : v14.16.1
**suitecloud-cli version** : 1.2.1

### Describe the bug
When  I attempt to deploy a project the command exits and console logs this "com.sun.net.ssl.internal.ssl.Provider" with no other information.

### To Reproduce
1. Run suitecloud project:deploy

It could be something with my Java install as it does work on a different computer. Any ideas how to resolve this?

**Comment by tourajvaziri** [comment]
hello @dturton
Are other commands also return a similar error (?) and does it only happen for a specific project or with other projects as well? (You can try with a new empty project  ) Also which java version do you have installed?

**Comment by dturton** [comment]
After several attempts of removing and re-installing JDK 11, it started working but I don't have the exact steps to reproduce it.

**Comment by philip-denys** [comment]
When uploading I get the same error

```terminal
$suitecloud file:upload --paths /SuiteScripts/timeapp/test.js
```
