### ISSUE TITLE
Cannot validate or deploy a custsecret_

### ISSUE THREAD

**Issue by Extend-Apps** [oracle/netsuite-suitecloud-sdk#370]
### Your environment
**OS** : macOS Big Sur (11.4)
**Node.js version** : v15.11.0
**suitecloud-cli version** : 1.2.1
**Terminal/CMD tool** : WebStormTerminal

### Describe the bug
Attempting to include a 'Secret' in our SuiteApp using Secrets Management (for distribution with our SuiteApp)

### To Reproduce
1. Create a Secret in NetSuite's "Secrets Management" tool
2. In SDF, add the customization object custsecret_example_id.xml, which contains the line <secret scriptid="custsecret_example_id"/>
3. Deploy (or Validate) against a different Netsuite Account
4. Fails with **_An error occurred during custom object validation. (custsecret_chr_secret) Details: Referenced secret: 'custsecret_chr_secret' is not available._**

![Screen Shot 2021-06-09 at 5 21 12 PM](https://user-images.githubusercontent.com/48653274/121431218-1f4e0580-c947-11eb-9b9b-1c5fa2782eb4.png)

### Actual Behavior
![Screen Shot 2021-06-09 at 5 17 15 PM](https://user-images.githubusercontent.com/48653274/121431115-fb8abf80-c946-11eb-8b1d-646f78658178.png)

### Expected Behavior
Since the 'secret' is correctly installed when packaged/distributed via the SuiteApp Control Center, I would expect the same behavior from SDF CLI.

### Additional context
Interestingly, if I 'package' the SuiteApp and include the custsecret, create a new version, and install the SuiteApp via 'SuiteApp Control Center', the secret is correctly created and works.

### Further
We have several developers working against the same code-base in different NetSuite accounts. Now, our authentication fails in all accounts other than the DEV account (where the secret was created).  We want to include this secret in the SuiteApp, but now have to revert not using the Secrets Management tool at all!

**Comment by alii-gator** [comment]
@Extend-Apps  This is not a defect of tool but server side error.

But anyway maybe there is something you can do.
For the marketplace`custsecret` is configured already. No additional steps required, and also as you said it works from marketplace.

But if you want to deploy from tool, there are some additional steps we need to perform.

How to configure:
Using the first account create a secret object in the UI (app/common/scripting/secrets/settings.nl).
In the restrictions, Check 'AVAILABLE TO SUITEAPP', then add:
1.      SUITEAPP ID: ID of the project you want to deploy the secret object with. (i.e. com.netsuite.suiteapp1)
2.      (IGNORE THIS STEP IF YOU ARE USING PRODUCTION ACCOUNT) ALLOW ON TEST ACCOUNTS: Specify the target account where you want the secret object to deploy to.
3.      After creating the secret object in the UI, import it to your SuiteApp project (i.e. com.netsuite.suiteapp1)
4.      Deploy the project to the target account.

**Comment by Extend-Apps** [comment]
@alii-gator , unfortunately, the solution you provided did not work.  Would I need to delete and recreate the secret completely?  I'm worried that doing that will break the installs into other accounts.

I'm happy to meet/screen share.  This issue has forced our multi-developer project to all use a single DEV account ... which has introduced a nightmare of coordination.

**Comment by alisyed-19** [comment]
@starlingjon This logic is handled on the server side, CLI is conveying the information.
Please contact Netsuite Support, and they will direct it to the proper team!
