### ISSUE TITLE
Jest Custom Output not working, seems the configuration for JEST is not getting passed in correctly

### ISSUE THREAD

**Issue by Rvice** [oracle/netsuite-suitecloud-sdk#391]
### Your environment
**OS** Windows 10
**Node.js version** : v16.5.0
**suitecloud-cli version** : 1.2.1
**Terminal/CMD tool** : CMD

### Describe the bug
I am attempting to use a custom reporter (https://www.npmjs.com/package/jest-teamcity-reporter), but it appears I cannot get the configuration settings to apply.

### To Reproduce
1. Add the following to the package.json 
    `"script": { jest --converage },
    "jest": {  "testResultsProcessor": "jest-teamcity-reporter" }`

### Actual Behavior
Standard output

### Expected Behavior
Expect to see TeamCity like outputs, but instead get the standard output. These include tags with the ##teamcity style output.

### Additional context
I am trying to use a custom formatter to send unit test results to TeamCity for pass/fail reporting. The workaround is to use the --json option in the "script" and looking for that in the string of failedtests:0 not matching.

 I tried to modify the jest.config.js to include the options with the module.export, but that breaks everything else. 

I then tried to add the Options in the suitecloud.config.js where the comment `// Jest configuration options.` exists without any luck as well.

Might be user error here as I am not completely familiar with Jest and how the module exports work. If I could just find the appropriate location for adding the Jest configurations that might resolve this issue.

**Comment by alii-gator** [comment]
@Rvice Can you share a complete package.json?

Which version of team-city-reporter are yo using?

**Comment by tourajvaziri** [comment]
Thanks @Rvice. Is this still an issue?

**Comment by Rvice** [comment]
I see where the problem comes in, it's in the jest.config.js

`module.exports = SuiteCloudJestConfiguration.build({
	projectFolder: cliConfig.defaultProjectFolder,
	projectType: SuiteCloudJestConfiguration.ProjectType.ACP,
	testEnvironment : 'node',
	testResultsProcessor: "jest-teamcity",
	coverageReporters: [
	"lcov",
	"text",
	"teamcity"
	],
	reporters: ["default", "jest-teamcity"]
});
`

If I move the reporters/testResultsProcessor/etc as the module.exports then it works. How can I get these additional config parameters to Jest? Is there a "passthrough" part of the SutieCloudJestConfiguration.build?

**Comment by Rvice** [comment]
This may have resolved the issue in the jest.config.js

```javascript
const nsExport = SuiteCloudJestConfiguration.build({
	projectFolder: cliConfig.defaultProjectFolder,
	projectType: SuiteCloudJestConfiguration.ProjectType.ACP
});

const jestParams = {
	"testEnvironment" : "node",
	"testResultsProcessor": "jest-teamcity",
	"coverageReporters": [
		"lcov",
		"text",
		"teamcity"
	],
	"reporters"	: ["default", "jest-teamcity"]
};

module.exports = {
	...nsExport,
	...jestParams
}
```

**Comment by Rvice** [comment]
Closing this issue as the jest.config.js steps above fixed it.
