### ISSUE TITLE
The JAR file is not available from this URL.

### ISSUE THREAD

**Issue by deus42** [oracle/netsuite-suitecloud-sdk#420]
### Your environment
**OS** : Ubuntu 20.04
**Node.js version** : e.g. 12.14.1
**suitecloud-cli version** : Run `suitecloud --version` to check the version

### Describe the bug
JAR file download link is broken

### To Reproduce
1. Run npm install -g @oracle/suitecloud-cli@1.1.2

### Actual Behavior
There was an error when downloading SuiteCloud SDK dependencies from https://system.netsuite.com/download/suitecloud-sdk/20.2/cli-2020.2.0.jar
The JAR file is not available from this URL.

### Expected Behavior
Library installs

### Additional context
Who is moving JAR files download links ???

**Comment by alii-gator** [comment]
The new version is out.
Try `Run npm install -g @oracle/suitecloud-cli`

**Comment by eklonsousa** [comment]
Is there any way to install the JAR file manually? The same behavior with 1.5.0 version:
![image](https://user-images.githubusercontent.com/45145781/165162686-96c26e26-9a8e-46bb-a415-a348a4722fe8.png)

**Comment by Rvice** [comment]
I have the same issue and it was working on 1.2 and possibly 1.4. Is there a regression here?

**Comment by eklonsousa** [comment]
> I have the same issue and it was working on 1.2 and possibly 1.4. Is there a regression here?

@Rvice , try to use "sudo" before any command line.

**Comment by Rvice** [comment]
I am using another user and I sudo into that user. We cannot elevate that user as it's part of our CI and deploy process. I did open  given this ticket is still closed
https://github.com/oracle/netsuite-suitecloud-sdk/issues/580
