### ISSUE TITLE
"Permission Violation: You need  the 'Web Site Management' permission to access this page." Error when deploying – permission must be attached directly to user and not by role

### ISSUE THREAD

**Issue by stevegoldberg** [oracle/netsuite-suitecloud-sdk#46]
I was a deploying a customisation with a **custcontenttype** record definition and the following error was being returned:

Details: Permission Violation: You need  the 'Web Site Management' permission to access this page. Please contact your account administrator.
File: ~/Objects/custcontenttype_3_t1358593_472.xml
Object: custcontenttype_3_t1358593_472 (cmscontenttype)

I checked the user I was using, and the roles it had assigned had the **Web Site Management** permission as one of its role's permissions. I tried again, it still failed.

I then assigned the permission directly to the user and I was able to deploy successfully.

I don't know if this an issue with the tool or NetSuite's APIs, but I encountered it while using the tool. Let me know if I should raise an issue in NetSuite instead.

**Comment by alii-gator** [comment]
@stevegoldberg This is not an issue coming from the tool itself but server side de. which role were you using? Developer role? If it was the developer role then the team responsible for this is already working on it.

**Comment by stevegoldberg** [comment]
I am using the developer role as one of the roles, but I also attached another custom role to my user which specifically had that permission and it wasn't being respected.

I figured it would probably be a server-side thing, but I wanted to check as I don't know if there's some code in the tool that checks roles/permissions. I'll close the issue, and you can delete it if you want.
