### ISSUE TITLE
VSCode Extension | Create SuiteScript File, incorrect template details generated (Client Script type)

### ISSUE THREAD

**Issue by dylbarne** [oracle/netsuite-suitecloud-sdk#461]
### Your environment
OS : Windows 10
Node.js version : v14.15.4
suitecloud-cli version : 1.3.0
Terminal/CMD tool : VSCode **Extension**

### Describe the bug
For VSCode extension, when running command "SuiteCloud: Create SuiteScript File" for Client Script type, incorrect template details are generated - with respect to JSDoc entry point function parameters.
Example: for `fieldChanged`/`validateField` , it is line & column, not lineNum & columnNum, `validateDelete` is missing lineCount etc.
_please also double-check all other script type templates though as well, comparing against documented entry point function parameters in HelpCenter "SuiteScript 2.x Script Types": .../app/help/helpcenter.nl?fid=chapter_4387172495.html_

### To Reproduce
1. In VSCode with latest Extension version installed, run command "SuiteCloud: Create SuiteScript File" for Client Script type
2. Go through steps to create new script file
3. Observe behavior described above

### Actual Behavior
Script template is generated with **incorrect** data with respect to documented script type entry point function parameters

### Expected Behavior
Script template should be generated with **correct** data with respect to documented script type entry point function parameters

### Additional context
Also a "nice-to-have" additional enhancement request: specifically when generating **Client** script type during the step for including SuiteScript API modules, should remove any modules that are only available server-side and only display those modules that are truly valid for client scripts.

Finally, the formatting generated is a bit off for me here:
![image](https://user-images.githubusercontent.com/66735423/133669728-fad5bb11-6537-4d3c-81e3-814856d400b4.png)
should be spaces after `@param`

**Comment by alii-gator** [comment]
@dylbarne We will investigate.

**Comment by lfpvillegas** [comment]
Hi @dylbarne 
I have been reviewing your issue and found the same discrepancies between JSDoc and the templates you have mentioned

While we are responsible of creating the file based on the Suitescript templates, the content itself is not part of the tools and should be treated via customer support.
You should create a customer service ticket to track this issue. 
Anyways, I will inform the team responsible of this content
Regards,
