### ISSUE TITLE
VSCode Extension | "Deploy Project" does not execute suitecloud.config command hooks

### ISSUE THREAD

**Issue by dylbarne** [oracle/netsuite-suitecloud-sdk#464]
### Your environment
**OS** : Windows 10
**Node.js version** : v14.15.4
**suitecloud-cli version** : 1.3.0
**Terminal/CMD tool** : VSCode Extension

### Describe the bug
A supported feature of the SuiteCloud Node Cli is command hooks (see "Suitecloud.config.js Customizations" section on https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_155931221634.html)
This works via Node Cli when executing via the command line, however, with VSCode extension this expected feature behavior is not mimicked - command hooks are not executed.

### To Reproduce
1. Run `suitecloud project:create -i` cmd to create a standard ACP project
2. Update suitecloud.config.js file to equivalent of contents attached
3. Run `suitecloud project:deploy -i` cmd to trigger `onCompleted` hook _(observe this is successful)_
4. Execute "SuiteCloud: Deploy Project" command from VSCode extension _(observe the deploy hook is not executed)_

### Actual Behavior
When running "SuiteCloud: Deploy Project" command from VSCode extension, the configured suitecloud.config hook is not executed.

### Expected Behavior
When running "SuiteCloud: Deploy Project" command from VSCode extension, the configured suitecloud.config hook should be executed as expected.

### Additional context
Example suitecloud.config.js
```javascript
const fs = require('fs');

module.exports = {
    defaultProjectFolder: 'src',
    commands: {
        'project:deploy': {
            onCompleted: (output) => {
                console.log('Eureka! The deployment was a success.');

                fs.writeFile('testDeploy.txt', 'test contents', (err) => {
                    if (err) {
                        throw err;
                    }

                    console.log('file saved!');
                });
            },
            onError: (error) => {
                console.log("Houston, we've had a problem here. The deployment failed.");
            },
        },
    },
};
```

**Comment by alii-gator** [comment]
@dylbarne Thanks for reporting this. We are working on it.

**Comment by davidecorreu** [comment]
Hi @dylbarne , the hooks are also executed from VSCode Extension, just keep in mind that the console.log() statements won't be shown in the Visual Studio Code SuiteCloud Output. 
The file testDeploy.txt has been created, but probably is not where you were expecting it.

I'll leave here another `suitecloud.config.js` sample so you can check that the hooks work fine from SuiteCloud CLI and SuiteCloud Extension for Visual Studio Code. Please check the content of the `testDeploy.txt` after running the deploy from each product, it will clarify that context of the execution is different in each case.


`suitecloud.config.js` sample:
```javascript
const fs = require("fs");
const path = require("path");

module.exports = {
	defaultProjectFolder: "src",
	commands: {
		"project:deploy": {
			onCompleted: (output) => {
				console.log("Eureka! The deployment was a success.");

				fs.writeFile(
					path.join(__dirname, "testDeploy.txt"),
					`test contents\ncurrrent working directory: ${process.cwd()}`,
					(err) => {
						if (err) {
							throw err;
						}

						console.log("file saved!");
					}
				);
			},
			onError: (error) => {
				console.log(
					"Houston, we've had a problem here. The deployment failed."
				);
			},
		},
	},
};

```

**Comment by dylbarne** [comment]
ah I see now, sorry for the false alarm! :) looks like can be resolved/closed

it would be a cool enhancement to expose some kind of logger that would display to the same VSCode output window as the other current logs for "SuiteCloud", if that is possible
