### ISSUE TITLE
VSCode Extension | Stuck on "Downloading SuiteCloud SDK dependencies..."

### ISSUE THREAD

**Issue by jsnzldy** [oracle/netsuite-suitecloud-sdk#470]
Just installed the VSCode Extention but the "Downloading SuiteCloud SDK dependencies..." task is not finishing. I also tried running commands in the command pallet but I'm getting below error.

command suitecloud.<nameOfCommand> not found

Also, the log file on the Extension Log Folder is empty.

**Comment by alii-gator** [comment]
Yes we are experiencing a minor issue. We are fixing it.

**Comment by alii-gator** [comment]
@jsnzldy should be fixed now. The dependecies should download if you restart vscode.

**Comment by MrRoot007** [comment]
i have the same error, 12/12/21

**Comment by alii-gator** [comment]
@MrRoot007 What is the output of `java -version` on your machine.
And also version of vscode?

**Comment by MrRoot007** [comment]
@alii-gator 
VSC-> 
Version: 1.62.3 (Universal), 
Java -> 
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

**Comment by alii-gator** [comment]
@MrRoot007 can you try with 1.61 version of vscode?

**Comment by MrRoot007** [comment]
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
i tried with 1.61.2 version, the same message: Before executing any SuiteCloud command, SuiteCloud SDK dependencies need to be validated. Try again in a few seconds.

**Comment by MUBUSHER** [comment]
@MrRoot007 any luck on this

**Comment by MrRoot007** [comment]
@MUBUSHER no, the issue persist, 
im using the CLI

**Comment by alii-gator** [comment]
@MUBUSHER @MrRoot007 
Can you please check if you uave any proxy configuration in vscode?

**Comment by MrRoot007** [comment]
![Captura de Pantalla 2021-12-12 a la(s) 23 22 38](https://user-images.githubusercontent.com/55603881/145757097-47b3f997-f6b6-46dc-aa5e-dfbd55fab4d1.png)
Sorry i tried with 1.63, the result is the same

**Comment by ekloneleuterio** [comment]
Same issue here with OSx. No proxy enabled

<img width="458" alt="image" src="https://user-images.githubusercontent.com/96245681/207905937-17eac6f8-cfdd-4582-8e12-02f6c7135bbf.png">

Does anybody figured out how to fix it?

**Comment by dominkodominka** [comment]
@ekloneleuterio don't you have any special character in your userprofile? I had to create new user with name which doesn't include any special chars to be able to download it

**Comment by MrRoot007** [comment]
> Same issue here with OSx. No proxy enabled
> 
> <img alt="image" width="458" src="https://user-images.githubusercontent.com/96245681/207905937-17eac6f8-cfdd-4582-8e12-02f6c7135bbf.png">
> 
> Does anybody figured out how to fix it?

Nope, I keep getting the same error

**Comment by ekloneleuterio** [comment]
> @ekloneleuterio don't you have any special character in your userprofile? I had to create new user with name which doesn't include any special chars to be able to download it

No special characters at all. 
The Netsuite community suggested to open a support ticket. 
The support suggested to reinstall VSCode and Extension. 

No success.

**Comment by dominkodominka** [comment]
Oh, sorry to hear that. I have no other idea except using alternative IDE.

**Comment by ekloneleuterio** [comment]
@dominkodominka , thanks mate.

I'll open a new issue.

**Comment by ekloneleuterio** [comment]
@MrRoot007 , in case you want to contribute:

https://github.com/oracle/netsuite-suitecloud-sdk/issues/662#issue-1516460961

Thank you!
