### ISSUE TITLE
Can the SuiteCloud Extension for Visual Studio Code be used without SDF?

### ISSUE THREAD

**Issue by amaddoxthevested** [oracle/netsuite-suitecloud-sdk#471]
Can the SuiteCloud Extension for Visual Studio Code be used without SDF?

Is there a SuiteCloud Extension for Visual Studio Code that can be used without SDF?

**Comment by amaddoxthevested** [comment]
Currently our NetSuite Scripts do not use SDF.  The scripts are in the Suite Scripts folder.  I would like to use the SuiteCloud VS Code extension to download the files to VS Code, but it is saying there is no manifest.xml file because there is no SDF.


Amanda  Maddox
Senior Consultant
t: 972.429.9025 | m: 972.791.8441
e: ***@***.*** | w: www.thevested.com
a: 1001 18th St., Plano, TX75074
The Vested Group is on TikTok! sheeesh

**Comment by alii-gator** [comment]
@amaddoxthevested 
All the tools delivered by Oracle NetSuite will expect that the project used is a SUITECLOUD project.
If your use case is that you want to Import and upload **SuiteScript** files to **SuiteScript** folder in the **filecabinet**, you can just create an **ACCOUNT CUSTOMIZATION PROJECT** in VSCODE.
Then import the files in that project and you can use that folder to upload files to SUITESCRIPTS folder.

1. Use **SuiteCloud Create Project**  -> To create a SuiteCloud project
2. Use **SuiteCloud Set Up account**  -> To authenticate your account and save it as default in this project. 
3.  Use  ****SuiteCloud Import Files / SuiteCloud Upload Files**
