### ISSUE TITLE
Cannot retrieve a disabled lineitem column "value" it returns the "internalId"

### ISSUE THREAD

**Issue by Rvice** [oracle/netsuite-suitecloud-sdk#480]
### Your environment
**OS** : Windows 10
**Node.js version** : 14.17.4
**suitecloud-cli version** : 1.3.0
**Terminal/CMD tool** : PowerShell

### Describe the bug
If a "lineItem" field is "disabled" via a UserEvent Script the following results in the internalId of a List instead of the "Value"
```
record.getSublistValue ({ sublistId: 'item',
      fieldId: 'custcol_mycol',
      line: 1
    });
```

One time I had multiple entries with duplicate Values and suspected this was the issue. I then purged that list and it seemed to work, but came back again.

### To Reproduce
1. Create a custom "Integer" list
1. Create a custom lineItem column with the list specified
1. Create a Fulfillment order and use a UserEvent script to "disable" the fields (have values that are part of the original list entered from the sales order or use defaults for the custom lineitem column)
1. Execute the script on getSublistValue and observe the internalId is returned (like the NetSuite Field Explorer shows)

### Actual Behavior
Returns the Internal ID of the ListItem

### Expected Behavior
Expect to get the Value of the ListItem, not the InternalId

### Additional context
Note, changing to getSublistText does return the proper value from the "disabled" field, which can then be parsed via parseInt() to get the desired value.

This has bitten us a few times now. Note, we have already decided against the "View Only" option as we cannot extract the value at all via the SuiteCloud CLI and used the UserEvent Disable approach.

**Comment by alii-gator** [comment]
This issue is not with the tool itself, The issues with server side issues/validations etc have to be reported to Netsuite support.
This is not a problem with the CLI itself. Its the response coming from Netsuite SDF.

Please open a ticket with NS Support.
