### ISSUE TITLE
suitecloud project:adddependencies returns Internal error encountered (Null pointer exception).

### ISSUE THREAD

**Issue by MiliGaricoits** [oracle/netsuite-suitecloud-sdk#481]
### Your environment
**OS** : iOS Big Sur
**Node.js version** : 12.22.3
**suitecloud-cli version** :1.2.1
**Terminal/CMD tool** : ZSH Terminal

### Describe the bug
running suitecloud project:adddependencies and returns Internal error encountered (Null pointer exception).

### To Reproduce
1. Run suitecloud project:adddependencies while standing on src folder

**Comment by alii-gator** [comment]
@MiliGaricoits This is in testing currently. Seem like the solution we are testing works well with some of the projects shared by users who were having the same issues. we will push the newer version with the fix. Hopefully it will fix the problem for you as well.

**Comment by alii-gator** [comment]
@MiliGaricoits @svs71180 Please try this with latest version of CLI `1.3.1`
