### ISSUE TITLE
Release notes are missing for 1.3.X verison

### ISSUE THREAD

**Issue by ludeknovy** [oracle/netsuite-suitecloud-sdk#483]
### Describe the bug
There are no release notes for recent version(s).
https://github.com/oracle/netsuite-suitecloud-sdk/releases

### Expected Behavior
Release notes are present.

**Comment by alii-gator** [comment]
@ludeknovy updated the release notes for `1.3.1`
[Release Notes 1.3.1](https://github.com/oracle/netsuite-suitecloud-sdk/releases/tag/%40oracle%2Fsuitecloud-cli%401.3.1)
