### ISSUE TITLE
Custom Form "Printing Fields" are not stored in the custform object

### ISSUE THREAD

**Issue by Rvice** [oracle/netsuite-suitecloud-sdk#484]
### Your environment
**OS** : Windows 11
**Node.js version** : 14.16.4
**suitecloud-cli version** : 1.3.1
**Terminal/CMD tool** : Powershell

### Describe the bug
Saving the custom form object, there are no printing settings stored. Ideally, this would store the various checkboxes to print and also any labeling changes for fields that are used.

### To Reproduce
1. Modify the Packing List Form and change the settings for things to print and rename the labels.
2. suitecloud object:import -i and pull the object that has the <script_id> of the form
3. Change the Printing Fields label for one of the items
4. suitecloud object:update -i  to All
5. Observe, no change.

### Actual Behavior
No change

### Expected Behavior
Expect to have the "Printing Fields" saved in the object to allow deploying to sandbox and production to match.

**Comment by alii-gator** [comment]
@Rvice This is not an issue with the tool, this is server side issue. Please contact NS Support.

**Comment by Rvice** [comment]
NS Support logged:
Enhancement # - 652567
Summary: Custom Transaction Form > Basic Printing Type > Expose Printing Fields object for customization

**Comment by alii-gator** [comment]
> NS Support logged: Enhancement # - 652567 Summary: Custom Transaction Form > Basic Printing Type > Expose Printing Fields object for customization

Closing this as well. The case is opened with NS Support.
