### ISSUE TITLE
Loading File Cabinet Folders Loads Forever 

### ISSUE THREAD

**Issue by faiwudevse** [oracle/netsuite-suitecloud-sdk#486]
### Your environment
**OS** : e.g. iOS MacOS Big Sur
**Node.js version** :  v16.13.0
**suitecloud-cli version** : 1.3.1
**Terminal/CMD tool** : Terminal
java version : java 11.0.12

### Describe the bug
For any commands, if you put -i which is the interactive mode, it will run forever that also taking CPU resources. It displays this message " Loading File Cabinet folders" and it loads forever. I tried vsCode extension as well, it has a similar issue. In the Vscode output tab, it outputs the message below
The remote server returned an error:

Read timed out. 

### To Reproduce
suitecloud file:list -i (it doesn't work)
suitecloud file:list --folder (it works)

**Comment by alii-gator** [comment]
@faiwudevse Can you try with Node14 LTS, which is recommended for this CLI.
When you do please re-install the CLI again.

**Comment by faiwudevse** [comment]
I did install node14 LTS (v 14.7.4), and ran this command npm install -g @oracle/suitecloud-cli  to reinstall cli . I still have the same issue in the interactive option when it comes to "Loading File Cabinet folders... ",  that just loads forever(I let it ran on the terminal like 6 hrs until I killed it). Other parts are working if that is not involving loading file cabinet folder.

**Comment by alii-gator** [comment]
@faiwudevse We are working on it. Currently this is in testing. We will have an update for you soon.

**Comment by alii-gator** [comment]
This should be fixed in latest.
@faiwudevse can you please confirm?

**Comment by faiwudevse** [comment]
@alii-gator Thanks the latest update work.
