### ISSUE TITLE
Publish VS Code Extension on Open VSX Registry (Add GitPod, VSCodium support)

### ISSUE THREAD

**Issue by michoelchaikin** [oracle/netsuite-suitecloud-sdk#489]
Is it possible for the VS Code extension to be published to Open VSX?

Open XSV is a vendor-neutral, open-source alternative marketplace for VS Code Extensions. Adding the extension to this registry will allow it to be used in fully open-source forks of VS Code such as VSCodium, gitpod etc.

Further information for publishing extensions to the registry is available here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by colivares82** [comment]
Hello @michoelchaikin, thanks for sharing this question.
I think it might depend on the term of usage you are looking for to achieve.

Would you like to have a quick call to clarify this point? Slack me!
