### ISSUE TITLE
Add ability to edit and delete authentication IDs in SuiteCloud Extension for Visual Studio Code

### ISSUE THREAD

**Issue by ghost** [oracle/netsuite-suitecloud-sdk#490]
### Summary
SuiteCloud Extension for Visual Studio Code has the ability to store authentication IDs, which are composed of an alias and NetSuite credentials. While users have the ability to create new authentication IDs, there is no supported way to edit or delete authentication IDs.

### Task
Add the ability to edit and delete individual authentication IDs in SuiteCloud Extension for Visual Studio Code, preferrably using the command palette.

**Comment by courchef** [comment]
Having to deal with frequent sandbox refresh, I need to re-create new access token and new authentication IDs on a monthly basis. This edit/delete ability would be really handy!

In the meantime, I found that the credentials are stored in the file `%USERPROFILE%\.suitecloud-sdk\credentials` on the Windows platform. Deleting the file and recreating new authentication IDs for production and sandbox is cleaner than having a bunch of obsolete authentication IDs.

**Comment by alii-gator** [comment]
This is WIP.

**Comment by alii-gator** [comment]
Newest version `1.3.1` has this functionality.
