### ISSUE TITLE
Suitecloud SDF stopped working after Monterey OS update

### ISSUE THREAD

**Issue by MiliGaricoits** [oracle/netsuite-suitecloud-sdk#491]
After upgrading to Monterey OS and Updating WebStorm to version 2021.2.3 the plugin stopped working. It looks installed and the account can be configured but we right-clicking on the project or any file, the NetSuite action is greyed out.

![image](https://user-images.githubusercontent.com/6898959/146375588-3a6ab28f-97b6-4253-95e6-ab1aa4ba9736.png)

**Comment by alii-gator** [comment]
This repository is for reporting bugs related to `SuiteCloud CLI for nodeJS`, and `SuiteCloud extension for VSCode`
Please report this issue  to NS Support and provide your project also to debug.

**Comment by alii-gator** [comment]
See requirements.
https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1529432517.html
