### ISSUE TITLE
SuiteCloud CLI for Node.js - project:deploy [-- dryrun] - Access Denied Error

### ISSUE THREAD

**Issue by LegitimatePassion** [oracle/netsuite-suitecloud-sdk#500]
### Your environment
**OS** : Windows 10
**Node.js version** : v14.17.1
**suitecloud-cli version** : 1.2.1
**Terminal/CMD tool** : gitbash

### Describe the bug
When I run the following command, I get an unexpected error. 

Command: `suitecloud project:deploy [-- dryrun]`
Error: **An unexpected error has occurred. Details: Access denied**

This doesn't make sense, because I'm able to run every other command with these account credentials without any errors.

### To Reproduce
1. Run suitecloud project:deploy [-- dryrun]

### Actual Behavior
Completes the account validation
When transitioning into beginning deployment > *** ERROR ***

### Expected Behavior
CLI will display a preview of the actions SDF will complete during deployment

### Additional context
I'd like to log all actions performed during the deployment process and catch any potential issues prior to deployment.

**Comment by LegitimatePassion** [comment]
My mistake, I figured out the issue. Closing this issue.

**Comment by AlexOlmoz** [comment]
Hi @LegitimatePassion, I have the same issue, maybe I'm doing the same mistake, can you explain me a little bit how do you solve this?
