### ISSUE TITLE
Dashboard Deploy Not Setting Up Reminder and Search Portlets

### ISSUE THREAD

**Issue by bernsteinmatt1717** [oracle/netsuite-suitecloud-sdk#501]
### Your environment
**OS** : e.g. macOS 12.0.1 (
**Node.js version** : 14.17.4
**suitecloud-cli version** : 1.3.2 
**Westorm Version** : 2021.2.3
**Terminal/CMD tool** : Webstorm SDF Plugin

### Describe the bug
When deploying a custom center tab and custom dashboard, the dashboard is not set up correctly. The reminders and search portlets are not set up with the search as specified in the XML. The XML is directly imported from a source account and deployed to a target account

### To Reproduce
1. Import custom center tab from the source account
2. Import custom dashboard from the source account
3. Deploy to the target account

### Actual Behavior
Target Account:
![image](https://user-images.githubusercontent.com/58997131/147760112-37e3ac85-cb51-4c59-8b6b-5177d2936185.png)

### Expected Behavior
Source Account:
![image](https://user-images.githubusercontent.com/58997131/147760157-060010bd-8168-474f-aa41-3349cd3774af.png)

### Additional context
NA

**Comment by alii-gator** [comment]
@bernsteinmatt1717 This platform is for reporting bugs related to SuiteCloud CLI for NodeJS and SuiteCloud Extension for VSCode.

The behavior you have described is not related to the tools it self but with NS Functionality. Please contact NS Support.
