### ISSUE TITLE
Ability to compare file with account

### ISSUE THREAD

**Issue by Godrules500** [oracle/netsuite-suitecloud-sdk#551]
Are there any plans in adding the option to compare the local file to the account file within VSCODE?

**Comment by dylbarne** [comment]
https://github.com/oracle/netsuite-suitecloud-sdk/blob/feature/vs-code/file-diff/packages/vscode-extension/src/commands/CompareFile.ts  ?
I would definitely like to see this enhancement/feature released as well :)

frequently I find it useful to do a quick comparison of what exists in local file storage vs NetSuite account fileCabinet

**Comment by patricklee-cnb** [comment]
definitely on board with this enhancement request

**Comment by rohitsharma11607471** [comment]
Would love to work on this feature :)

**Comment by alii-gator** [comment]
Newest version 1.3.1 has this functionality.
