### ISSUE TITLE
Fails when issuing tokens

### ISSUE THREAD

**Issue by jtraugott** [oracle/netsuite-suitecloud-sdk#56]
Process fails when issuing tokens for a netsuite account. 'SDK exited with code 127 command not found'

![image](https://user-images.githubusercontent.com/59929927/75817694-40e03a80-5d5d-11ea-8702-a3a020df4cee.png)

**Comment by vic-nik** [comment]
Hello @jtraugott ,
Thank you for your feedback!
From your screenshot I understand you are using the code from master branch that has code for 19.2 version which was not officially released, this code is outdated, all active development happens in /dev branch.
We will officially release 20.1 version of suitecloud-cli in npmjs.com in the following weeks, the latest code will be merged into master then.
If you would like to use suitecloud-cli already I would recommend installing from /dev branch.
Closing this issue as outdated.
