### ISSUE TITLE
Cannot complete browser-based account setup (VSCode + WSL)

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-sdk#574]
### Your environment
**OS** :  Windows 10, Ubuntu 20 in WSL2.
**Node.js version** : e.g. 16.13.1
**suitecloud-cli version** : 1.3.2
**Terminal/CMD tool** :  WSL in VSCode

### Describe the bug
Using VSCode + WSL, trying to add a new account via browser session goes nowhere. It seems like it's trying to launch the browser in WSL which won't work (no GUI)

### To Reproduce
1. Open a WSL based project in VSCode
2. attempt to **"SuiteCloud:  Setup Account"**

### Actual Behavior
Step 2 fails. Eventually with an error like 

```
Can't connect to X11 window server using '172.21.48.1:0' as the value of the DISPLAY variable.
```

### Expected Behavior
Use the existing Windows browser session to setup account.

**Comment by alii-gator** [comment]
@ShawnTalbert We don't support WSL officially.
I think WSL doesn't support browser by default. You can check some solutions to use browser in WSL mentioned in this [article ](https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux)

**Comment by ShawnTalbert** [comment]
I don't see why WSL should be involved here?

 If webstorm is running in windows, can it not launch a windows browser?

**Comment by gbs4ever** [comment]
I am having similar issue , as version 2024.2 removed the option to saved TBA token issued in Netsuite,    Browser-based authentication, returns this error Web browsing is not supported on this system.

**Comment by alisyed-19** [comment]
@gbs4ever Check the documentation for Machine to machine authentication. This is designed for authentication without browser!
