### ISSUE TITLE
Sync reports and searches with SDF

### ISSUE THREAD

**Issue by manueltoniato** [oracle/netsuite-suitecloud-sdk#591]
Last week I converted a Suitebundle in a SDF zip files.
The suitebundle contained saved searches and reports but when I tried to deploy that project I got validation problems and there was no way to get it to work.
![image](https://user-images.githubusercontent.com/822474/177377347-0c15577b-af14-4ae6-a178-06734d79ef82.png)
I thinks that, as Suitebundler did, SDF should also allow to sync and deploy both saved searches and reports.

Thanks!

**Comment by alii-gator** [comment]
This issue is not with the tool itself, The issues with server side validations etc have to be reported to Netsuite support.
This is not a problem with the CLI itself. Its the response coming from Netsuite SDF.

Please open a ticket with NS Support.
