### ISSUE TITLE
SuiteCloud: Compare with Account files VSCode extension command error

### ISSUE THREAD

**Issue by kostiato** [oracle/netsuite-suitecloud-sdk#613]
I get _Invalid option "-allowforsuiteapps"._ while trying to execute this new command.
What are the requirements for using it. I can not find any documentation about this useful functionality.

**Comment by kostiato** [comment]
@karl-anthony-ng yes)

**Comment by tourajvaziri** [comment]
Hi @kostiato,
Which OS are you using? and what type of project is it? SUITEAPP or ACCOUNTCUSTOMIZATION? Also, can you please share a screenshot of where the error is happening in vscode?

**Comment by alii-gator** [comment]
@kostiato Apart from the information requested above, can you please try to uninstall the plugin and install it again?

**Comment by kostiato** [comment]
@alii-gator uninstalled, restarted VS Code, installed, restarted VS Code again
![image](https://user-images.githubusercontent.com/30745425/190155788-c57fe9ef-e5ee-4f6e-b723-021939039767.png)
Right click on any file from File Cabinet and select 'Compare with Account file' or select the same command from Command Palette with active file opened from the project displays error in SuiteCloud ouput ^^^ 
@tourajvaziri 
```
VS Code Version: 1.71.1
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.8
Sandboxed: No
```

**Comment by dylbarne** [comment]
I am experiencing the same issue.

maybe needs newer version of SuiteCloud CLI for Java cli-2022.2.0.jar to be released?
doesn't seem like is recognizing as valid cli command option when tries to import file for compare
https://github.com/oracle/netsuite-suitecloud-sdk/blob/release/22.2/packages/node-cli/src/commands/file/import/ImportFilesAction.js

executing adhoc command `sdfcli importfiles -allowforsuiteapps` produces same "Invalid option" error, when running against jar downloaded from https://system.netsuite.com/download/suitecloud-sdk/cli/java/latest/sdf-cli.zip

**Comment by alii-gator** [comment]
@dylbarne @kostiato 

Please be sure to have java 17 installed on your machine and then install the plugin again!

**Comment by dylbarne** [comment]
I tried uninstalling/reinstalling the vscode extension, didn't seem to affect things

running `java -version` gives me back:
_java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)_

**Comment by Jodaviro** [comment]
I have the same error.
I updated java to version 17, tried uninstalling/reinstalling the vscode extension.  I can use all of the commands except by the new "SuiteCloud: Compare with Account files".

**Comment by thiagopias** [comment]
I am just having this issues now. it started this afternoon.

![Screen Shot 2022-09-14 at 18 16 21](https://user-images.githubusercontent.com/29020490/190267962-be168ecd-568d-4825-bbe3-555a84526db2.png)
![Screen Shot 2022-09-14 at 18 16 06](https://user-images.githubusercontent.com/29020490/190267981-dfce8c72-558a-40df-9ae8-264bac5230e8.png)

**Comment by thiagopias** [comment]
Thank you . I appreciate that.
After I have those errors I realized I need update my java to version 17
for the plugin's new version.
Well I, could work around upgrading to the previous version of the plugin.
In the near feature, I'll trying the new version as it brings new
interesting features.
Thanks once again for your help.

**Comment by Jodaviro** [comment]
Thank you. 1.3.1 solved the error.

**Comment by thiagopias** [comment]
Thank you for your response!
