### ISSUE TITLE
Before executing any SuiteCloud command, SuiteCloud SDK dependencies need to be validated. Try again in a few seconds.

### ISSUE THREAD

**Issue by GabrielGorta** [oracle/netsuite-suitecloud-sdk#622]
### Your environment
**OS** : Windows 11
**Node.js version** : 18.6.0
**suitecloud-cli version** : 1.5.0
**VSCode version**: 1.71.2
**Terminal/CMD tool** : PowerShell/VSCodeTerminal
**Extension version**: 1.3.1

### Describe the bug
At file upload I get error:

```
Before executing any SuiteCloud command, SuiteCloud SDK dependencies need to be validated. Try again in a few seconds.
```

### To Reproduce
1. In some file, press CTRL+SHIFT+U or use F1 and select SuiteCloud Upload File (suitecloud.updatefile) command.

### Actual Behavior
![image](https://user-images.githubusercontent.com/112625511/190964621-87c052f7-854e-44b3-b534-9df3603087a4.png)

### Expected Behavior
File uploaded

### Additional context
Trying again later doesn't help.

**Comment by Elroban85** [comment]
I just encountered the same and tried to revert back to 1.3.0
Didn't solve my issue but I did encounter a message saying my Java JDK was outdated. After updating this, and reloading VS Code, the extension functions were working again.

**Comment by alii-gator** [comment]
@GabrielGorta Can you confirm if you have java 17 LTS installed?

**Comment by GabrielGorta** [comment]
After installing Java 17, it works fine.... but what a error message. It could say "update Java".
