### ISSUE TITLE
Error:: Access Denied when deploying project

### ISSUE THREAD

**Issue by cmccannbrite** [oracle/netsuite-suitecloud-sdk#627]
### Your environment
**OS** : Windows 11 / WSL2 Ubuntu 22.04.1
**Node.js version** : 16.14.0
**suitecloud-cli version** : 1.6.1
**Terminal/CMD tool** : WSL / ZSH

### Describe the bug
Getting the following error when trying to deploy project:

```
DEPLOYMENT PREVIEW


*** ERROR ***

An unexpected error has occurred.
Details: Access denied
```

### To Reproduce
1. Run suitecloud project:deploy --dryrun or suitecloud project:deploy -i

### Actual Behavior

```
The preview process has encountered an error.
Deployment preview for ...
Validate manifest -- Success
Validate deploy file -- Success
Validate configuration -- Success
Validate objects -- Success
Validate files -- Success
Validate folders -- Success
Validate translation imports -- Success
Validation of referenceability from custom objects to translations collection strings in progress. -- Success
Validate preferences -- Success
Validate flags -- Success
Validate for circular dependencies -- Success
Validate account settings -- Success
Validate Custom Objects against the Account -- Success
Validate file cabinet items against the account -- Success
Validate translation imports against the account -- Success
Validation of references to translation collection strings against account in progress. -- Success


DEPLOYMENT PREVIEW


*** ERROR ***

An unexpected error has occurred.
Details: Access denied
```

### Expected Behavior
Project that validates should deploy

**Comment by cmccannbrite** [comment]
That seems to have fixed the issue.  Is this a known issue that I have overlooked?  Is there a setting to stop the project from creating that file in the first place?

Thanks for the help on this!

**Comment by alii-gator** [comment]
We will check if we can remove that folder, But for now you are not blocked. So will close this issue.
