### ISSUE TITLE
project:adddependencies doesn't detect a subtab object dependency 

### ISSUE THREAD

**Issue by magic-madrigal** [oracle/netsuite-suitecloud-sdk#649]
### Your environment
**OS** : Ventura 13.0.1 (22A400)
**Node.js version** : v18.11.0
**suitecloud-cli version** : 1.6.2
**Terminal/CMD tool** : Terminal/iTerm

### Describe the bug
Command `suitecloud project:adddependencies` does not discover an object dependency. This is a transactionbodycustomfield object, and within the subtab element, there is a [scriptid=XXX] that does not get picked up. This also isn't picked up by `suitecloud project:validate`. Once `suitecloud project:deploy --validate` is run, the error appears.

### To Reproduce
1. Run `suitecloud project:adddependencies`
2. Run `suitecloud project:validate`
3. Run `suitecloud project:deploy --validate`

### Actual Behavior
 `suitecloud project:adddependencies` &  `suitecloud project:validate` miss a necessary dependency and `suitecloud project:deploy` fails.

### Expected Behavior
It would be ideal if the dependency file were added to the manifest before deploy.

### Additional context
none at this time.

**Comment by lfpvillegas** [comment]
Hi @magic-madrigal 

We are reviewing past issues and I have not been able to replicate this issue.
Could you please try it with last Suitecloud CLI version? 
If the error persists Could you please share the files that produce this error?

Thanks.
