### ISSUE TITLE
Missing selectLine method in stubs/record/RecordInstance mock stub

### ISSUE THREAD

**Issue by jeremyhac** [oracle/netsuite-suitecloud-sdk#650]
### Your environment
**OS** : e.g. iOS Mohave 10.14.6 /Windows 10/Ubuntu 16.04
**Node.js version** : e.g. 12.14.1
**suitecloud-cli version** : Run `suitecloud --version` to check the version
**Terminal/CMD tool** : e.g. PowerShell/WebStormTerminal/VSCodeTerminal/iTerm

### To Reproduce
1. Run suitecloud {command} -i

**Comment by jeremyhac** [comment]
In the [stubs/record/RecordInstance.js file](https://github.com/oracle/netsuite-suitecloud-sdk/blob/master/packages/unit-testing/stubs/record/RecordInstance.js), there is no reference to the `selectLine` method, meaning we cannot mock this function, even though it should be part of the RecordInstance module.

**Comment by vic-nik** [comment]
@jeremyhac Thank you for identifying the missing function. The fix is included in the pull request 644.
