### ISSUE TITLE
[Question] Does SDF perform any caching of files?

### ISSUE THREAD

**Issue by ericgrubaughcompass** [oracle/netsuite-suitecloud-sdk#656]
### Your environment
**OS** : Ubuntu 22.04
**Node.js version** : 18.8.0
**suitecloud-cli version** : 1.6.2
**Terminal/CMD tool** : Bash

### Describe the bug
Does SDF or NetSuite perform any caching of file contents for deployment purposes?

### To Reproduce

Unknown

### Actual Behavior
Recently, we observed the following behavior during an SDF deployment:

1. We added a new function to one of our source files, and we added an invocation of that function in a separate source file.
2. Those changes were committed and pushed to our `master` branch.
3. Our CircleCI system pulled the `master` branch and ran `suitecloud project:deploy` to our Production account.
4. We began to see errors in our Production account that the new function was being invoked but did not exist. i.e. From Step 1, the function had *not* been added to the first source file, but the function invocation *had* been added to the second source file.
5. We verified that the file(s) in question was listed in the Deployment Audit Trail and the output from the `project:deploy` command as expected.
6. Two separate developers found that if we Viewed the file in the File Cabinet, the new function was not present in the file; however, if we Edited the file in the File Cabinet, the new function was present.
7. After editing and saving the file _without making any changes_, the errors stopped.
8. The System Notes for the file show that the file contents were in fact changed by the deployment, but then the contents changed again after editing and saving the file _without making any changes_: ![sdf-dec](https://user-images.githubusercontent.com/96068756/207657619-699de556-d41c-40d2-a2d7-5121ad3faeaf.png)

### Expected Behavior
The correct version of every file gets deployed and used immediately, not any intermediate or cached versions.

**Comment by Extend-Apps** [comment]
+1 on this one.  Its been a major source of issue for us as well.

**Comment by ericgrubaughcompass** [comment]
> +1 on this one. Its been a major source of issue for us as well.

@Extend-Apps Have you found/built anything to mitigate the issue or at least identify that it has happened?

**Comment by Extend-Apps** [comment]
No.  We perform the same tasks as you.  It's incredibly frustrating to include in your development workflow to edit/save files in the NetSuite File cabinet if you experience unexpected behavior.

**Comment by tourajvaziri** [comment]
Hello,
From reading the steps provided, this is not an issue related to the suitecloud sdk tool but Netsuite. I suggest that you open an issue for NetSuite support so that it is assigned to the correct team.

**Comment by alii-gator** [comment]
Closing after comment from @tourajvaziri 

> Hello, From reading the steps provided, this is not an issue related to the suitecloud sdk tool but Netsuite. I suggest that you open an issue for NetSuite support so that it is assigned to the correct team.

Closing after comment from @tourajvaziri

**Comment by ericgrubaughcompass** [comment]
> Hello, From reading the steps provided, this is not an issue related to the suitecloud sdk tool but Netsuite. I suggest that you open an issue for NetSuite support so that it is assigned to the correct team.

Could you help me understand how this would not be considered a SuiteCloud SDK issue? In Step 3, we asked the SuiteCloud SDK to deploy a file to our NetSuite account. In Step 4, we see that the SuiteCloud SDK *did not* deploy that file to our account, yet in Step 5, SuiteCloud SDK reports a successful deployment of the file.
