### ISSUE TITLE
Bundle Objects Install Feature is missing

### ISSUE THREAD

**Issue by rnawaz12** [oracle/netsuite-suitecloud-sdk#699]
## Bundle Objects for SDF Project using Nodejs CLI
It seems like there is a difference in the way Eclipse IDE and VS Code Extension or Node.js CLI handle importing the bundle object for SDF projects. While Eclipse allows for this, it appears that VS Code does not have the same capability.

**Comment by rnawaz12** [comment]
Thank you @tourajvaziri, I've been a long-time user of SDF and I appreciate the ability to generate an object.xml file for all record types via the command palette(VS Code Extension), as I can currently do in the Eclipse IDE. Also, need to improve the forms.xml objects, most of the time project:validate failed due to errors like:
![image](https://user-images.githubusercontent.com/91124953/231246850-c162fd6d-30fb-4559-a9a9-9a253bc3e4c0.png)
and
![image](https://user-images.githubusercontent.com/91124953/231246955-b4821959-0813-4f6e-8370-8128715e02e6.png)

**Comment by tourajvaziri** [comment]
Hello @rnawaz12, that would be a great addition to vscode and indeed we have an open ticket to track it: https://github.com/oracle/netsuite-suitecloud-sdk/issues/530

About the improvements to the errors, is the problem specific to forms.xml object or in general? And are the errors displayed incorrect?
