### ISSUE TITLE
Unable to upload file to file cabinet due to file path format.

### ISSUE THREAD

**Issue by JacobSapeckyRS** [oracle/netsuite-suitecloud-sdk#711]
### Your environment
**OS** : Windows 11
**Node.js version** : 18.16.0
**suitecloud-cli version** : 1,4,1
**Terminal/CMD tool** : VSCodeTerminal 

### Describe the bug
I can create a project and set up the account. I can also pull files from the NetSuite file cabinet. However, When creating a new file or attempting to upload a file, it is not working. I get the following errors. 

![suiteclouderror](https://user-images.githubusercontent.com/105794289/233090525-0fa99a25-7762-4e2d-bef8-026349d8ceb9.png)

 The first error is when trying to create a new suitescript file. The second is when trying to upload. I noticed on a colleagues computer when he uploads it is not the double slashes.
### To Reproduce
1. Installed VSCODE and SuiteCloud extension
2. Created a SuiteCloud project
3. Set up account, account set up successfully.
4. When using create or upload it will not work.

### Actual Behavior
Errors out with the screenshots above

### Expected Behavior
Be able to create or upload scripts to file cabinet.

### Additional context
The user with the error is an administrator and has all necessary permissions.

**Comment by MJensen6889** [comment]
Same here. Able to import fine, but the upload file request seems to be doubling the slashes in the path making it invalid. Tried creating new projects on multiple versions of the suitecloud extension, but still haven't been able to fix the issue. I also switched to use CLI. Hopefully they get this resolved.

**Comment by adock27** [comment]
To solve the problem you should use Java 17.2 Jdk, It works for me.

**Comment by MJensen6889** [comment]
Yep, that fixed it for me as well. 17.0.2 - Thanks!

**Comment by tourajvaziri** [comment]
Hello @adock27 @HanzChen @MJensen6889,
Thanks for providing a fix and verifying that it is working for you. Just to understand it, it seems that using Java 17.0.2 solves the issue. If yes, which version of Java were you using prior to that? (when you were getting the error) 
Did you have to upgrade to a downgrade java to make it work?

**Comment by tourajvaziri** [comment]
Hello @adock27 @HanzChen @MJensen6889, any updates here?

**Comment by tourajvaziri** [comment]
I will close this. If you have updates on this feel free to include it here.

**Comment by khaleeqozaman** [comment]
I had the same issue and installing Java 17.0.2 version fixed the issue. Previously, Java 17.0.7 version was installed.
