### ISSUE TITLE
The file cabinet path "\\SuiteScripts\\test.js" is invalid. It must refer to a file in a "/SuiteScripts" folder or in any "/Web Site Hosting Files" subfolder.

### ISSUE THREAD

**Issue by xela-quartz** [oracle/netsuite-suitecloud-sdk#723]
### Your environment
**OS** : Windows 11
**Node.js version** :n/a
**suitecloud-cli version** : n/a
**Terminal/CMD tool** : Visual Studio - SuiteCloud Extension for Visual Studio Code

### Describe the bug
When tryin to create a suitescript file via the palette (SuiteCloud: Create SuiteScript File), I get this error: The file cabinet path "\\SuiteScripts\\test.js" is invalid. It must refer to a file in a "/SuiteScripts" folder or in any "/Web Site Hosting Files" subfolder.

### To Reproduce
1. Open Command Palette (Ctrl + Shift + P)
2. Select SuiteCloud: Create SuiteScript File
3. Select script type 
4. Select modules
5. Select File Cabinet folder
6. Type a name for the file 
7. Click OK

### Actual Behavior
![image](https://user-images.githubusercontent.com/93782072/236312442-42d42d35-dbbc-4162-beb4-9250209d403f.png)
![image](https://user-images.githubusercontent.com/93782072/236312512-12e4a859-18ab-471c-9ca4-bac40d48b884.png)

In Output tab: The file cabinet path "\\SuiteScripts\\test.js" is invalid. It must refer to a file in a "/SuiteScripts" folder or in any "/Web Site Hosting Files" subfolder.

### Expected Behavior
Successfully create a script file containing the template of the script type

**Comment by davidecorreu** [comment]
@xela-quartz 
This seems to be also related to https://github.com/oracle/netsuite-suitecloud-sdk/issues/711 which has already been tracked.
We'll also keep an eye on the **SuiteCloud: Create SuiteScript File** command of the suitecloud extension for vscode.
