### ISSUE TITLE
Getting "No folders available." error message when running Import Files

### ISSUE THREAD

**Issue by abarylak** [oracle/netsuite-suitecloud-sdk#725]
### Your environment
**OS** : Windows 11
**Node.js version** : ?
**suitecloud-cli version** : None
**Terminal/CMD tool** : PowerShell
VScode Extension version: 1.4.2

### Describe the bug
Just starting to try to get this Extension working for VScode.  Got connected to my sandbox account using my Administrator role.  However, when i try running the Import Files command, i get a "No folders available." error message.  Due to the absence of any other way to ask about this that i can find, i decided to create this bug report.  Probably not a bug, but i may be missing something, but i've reviewed the prerequisites over and over, and i don't know what i'm missing.

### To Reproduce
1. Connect an account to a new project
2. Right click the "SuiteScripts" folder
3. Select "Import Files"

### Actual Behavior
Get the error "No folders available."
![image](https://github.com/oracle/netsuite-suitecloud-sdk/assets/1834888/a15a68b7-e1c2-4a88-9566-cb8e2908e96e)

### Expected Behavior
Should give me some options to download folders and files from my account.

### Additional context
Sorry if this is not the right place to post this, but i'm at a loss, i've been reviewing the help documentation for days and have not figured out what i may be missing.  I had originally tried v1.3.2 of the SuiteCloud Extensions for VScode due to an issue i was originally having connecting to the account, but i am connected not, and after getting this error on 1.3.2, i upgraded back to 1.4.2 and still am getting the same error.

**Comment by abarylak** [comment]
I may have a suspicion of why this is the case.  I selected the "Account Customization Project" type when creating the project in VScode.  I did this because i thought it would behave just like the old Eclipse addon and allow me to just edit the scripts and stuff in our account as needed.  However, it looks like that type is also an SDF project type.  We don't have SDF enabled on our account.

I may just need confirmation that in order to use the VScode extension, SDF is required?  Unless i'm still missing something.  Let me know.  Thanks.

**Comment by davidecorreu** [comment]
Hi @abarylak ,
You were right on your suspicion, you must have the `SuiteCloud Development Framework` feature enabled in your account to see the available folders/files to import.

To do so:
 - navigate to `Setup > Company > Enable Features > SutieCloud tab`
 - select the `SuiteCloud Development Framework` checkbox
 - accept the license agreement
 - click on save button
