### ISSUE TITLE
Bump vm2 to resolve critical CVE

### ISSUE THREAD

**Issue by ZackKanter** [oracle/netsuite-suitecloud-sdk#730]
There's [a Dependabot PR open](https://github.com/oracle/netsuite-suitecloud-sdk/pull/726) for bumping `vm2` from `3.9.17` to `3.9.18`. This would resolve t[he critical CVE](https://github.com/advisories/GHSA-whpj-8f3w-67p5) in vm2 3.9.17 that currently affects this repo. It would be great to get this merged ASAP.

**Comment by lfpvillegas** [comment]
Hi Zack,
Thanks for pointing out.
Yes we are in the process of releasing a new version that even removes completely vm2. It would be ready soon.
Regards

**Comment by lfpvillegas** [comment]
Hi again,
We have just released [version 1.7.3](https://www.npmjs.com/package/@oracle/suitecloud-cli) on npm. Please check it out.
This version removes entirely vm2 dependency so the CVE does not longer apply on it.
Regards.

**Comment by ZackKanter** [comment]
> Hi again,
> We have just released [version 1.7.3](https://www.npmjs.com/package/@oracle/suitecloud-cli) on npm. Please check it out.
> This version removes entirely vm2 dependency so the CVE does not longer apply on it.
> Regards.

This worked as expected – thank you!

<img width="926" alt="Screenshot 2023-05-26 at 8 16 55 AM" src="https://github.com/oracle/netsuite-suitecloud-sdk/assets/2780696/386754f8-af95-4dbb-9903-9d1f34fa861d">
