### ISSUE TITLE
account:savetoken error

### ISSUE THREAD

**Issue by sirvine-r7** [oracle/netsuite-suitecloud-sdk#746]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.8.0

### Operating system

linux

### Node Version / VSCode Version

v18.16.1

### JAVA Version

17.0.7

### Bug description

When using the latest version of suitecloud-cli we get the following error while running account:savetoken

`Something went wrong when trying to save credentials. Contact support`

The same command, when ran using 1.7.3, works as expected.

### Steps To Reproduce

1. run suitecloud project:create --type ACCOUNTCUSTOMIZATION
2. run account:savetoken
3. error 'Something went wrong when trying to save credentials. Contact support'

### Actual Output

Something went wrong when trying to save credentials. Contact support

### Expected Output

The account has been successfully set up.

**Comment by alii-gator** [comment]
@sirvine-r7 which linux flavor do you have?

**Comment by christopherwxyz** [comment]
@alii-gator -- i'm also having this issue with the same message. running the CLI through macOS 13.5 is fine. running the CLI through a docker container results in the error above. My linux environment is: `FROM node:16.18.0-alpine3.16`

**Comment by alii-gator** [comment]
Hello, please use `npm i -g @oracle/suitecloud-cli@1.7.3` while we investigate this behavior!

**Comment by karl-anthony-ng** [comment]
Can you try adding the following to your Docker file? This should be added before running a suitecloud-cli command.
`RUN apk update
RUN apk add bash
RUN apk add dbus
RUN dbus-uuidgen --ensure`

**Comment by sirvine-r7** [comment]
confirming that adding in the dependency for dbus resolved the issue

**Comment by murilolobato** [comment]
I'm facing the same issue while using the latest Java CLI tool.

When I run the following command on the openjdk 17 docker container:
```
./bin/sdfcli/sdfcli authenticate -savetoken -url SUITECLOUD_URL -account SUITECLOUD_ACCOUNT -authid SUITECLOUD_AUTHID -tokenid SUITECLOUD_TOKEN_ID -tokensecret SUITECLOUD_TOKEN_SECRET
```

I got the response:
```
Something went wrong when trying to save credentials. Contact support.
```

But with the same CLI tool, on my MacOS it works correctly.

**Comment by murilolobato** [comment]
I could confirm that with the lastest Java CLI the problem occurs:

https://system.netsuite.com/download/suitecloud-sdk/cli/java/latest/sdf-cli.tar.gz

And with the previous version it doesn't:

https://system.netsuite.com/download/suitecloud-sdk/cli/java/23.1/sdf-cli.tar.gz

So I fixed my problem using the previous version. 

I also noticed, that the NetSuite documentation contains broken links for the CLI files. The link description is different from the actual href. And some URLs doesn't exist at page:

https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1489072409.html#procedure_1549982040

```
Windows latest - Correct:
<a href="https://system.netsuite.com/download/suitecloud-sdk/cli/java/latest/sdf-cli.zip" target="_blank">https://system.netsuite.com/download/suitecloud-sdk/cli/java/latest/sdf-cli.zip</a>

Linux latest - Correct:
<a href="https://system.netsuite.com/download/suitecloud-sdk/cli/java/latest/sdf-cli.tar.gz" target="_blank">https://system.netsuite.com/download/suitecloud-sdk/cli/java/latest/sdf-cli.tar.gz</a>

Windows 23.2 - Wrong and file doesn't exists:
<a href="https://system.netsuite.com/download/suitecloud-sdk/cli/java/20.2/sdf-cli.zip" target="_blank">https://system.netsuite.com/download/suitecloud-sdk/cli/java/23.2/sdf-cli.zip</a>

Linux 23.2 - Wrong and file doesn't exists:
<a href="https://system.netsuite.com/download/suitecloud-sdk/cli/java/20.2/sdf-cli.tar.gz" target="_blank">https://system.netsuite.com/download/suitecloud-sdk/cli/java/23.2/sdf-cli.tar.gz</a>

Windows 23.1 - Wrong href but file exists:
<a href="https://system.netsuite.com/download/suitecloud-sdk/cli/java/20.2/sdf-cli.zip" target="_blank">https://system.netsuite.com/download/suitecloud-sdk/cli/java/23.1/sdf-cli.zip</a>

Linux 23.1 - Wrong href but file exists:
<a href="https://system.netsuite.com/download/suitecloud-sdk/cli/java/20.2/sdf-cli.tar.gz" target="_blank">https://system.netsuite.com/download/suitecloud-sdk/cli/java/23.1/sdf-cli.tar.gz</a>
```

**Comment by murilolobato** [comment]
I also could confirm that with the latest Java CLI and the dbus package installed, the problem won't occur.
