### ISSUE TITLE
Inconsistent file naming convention cause crash on case-sensitive systems.

### ISSUE THREAD

**Issue by hannu-forsten** [oracle/netsuite-suitecloud-sdk#751]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Unit Testing

### Version of the SuiteCloud Tool

1.3.1

### Operating system

Linux and UNIX

### Node Version / VSCode Version

v16.17.1

### JAVA Version

17

### Bug description

suitecloud-unit-testing/stubs/datasetLink/datasetLink.js
suitecloud-unit-testing/stubs/dataset/dataset.js

should be 
suitecloud-unit-testing/stubs/datasetLink/DatasetLink.js
suitecloud-unit-testing/stubs/dataset/Dataset.js

### Steps To Reproduce

1. Use Unix/Linux
2. Write script `define(['N/workbook'], (wb) => {})`
3. npm test 

### Actual Output

```
Cannot find module '../datasetLink/DatasetLink' from 'node_modules/@oracle/suitecloud-unit-testing/stubs/workbook/Pivot.js' 
```

or 
```
Cannot find module '../dataset/Dataset' from 'node_modules/@oracle/suitecloud-unit-testing/stubs/workbook/Pivot.js'
```

### Anything else?

Workaround: 
Before `npm test`

```
- mv ./node_modules/@oracle/suitecloud-unit-testing/stubs/dataset/dataset.js ./node_modules/@oracle/suitecloud-unit-testing/stubs/dataset/Dataset.js
- mv ./node_modules/@oracle/suitecloud-unit-testing/stubs/datasetLink/datasetLink.js ./node_modules/@oracle/suitecloud-unit-testing/stubs/datasetLink/DatasetLink.js
```

**Comment by davidecorreu** [comment]
Hi @hannu-forsten ,

We have realized that the import from `@oracle/suitecloud-unit-testing/stubs/workbook/Pivot.js` is wrong and should reference the "instance" objects. 

The beginning of the first line for that file should be:
`define(['../dataset/DatasetInstance', '../datasetLink/DatasetLinkInstance', ... `

We'll work on fixing this bug, and some others we have detected after your comment.
Thanks for your input 😄

**Comment by davidecorreu** [comment]
HI @hannu-forsten ,

We have just published **@oracle/suitecloud-unit-testing** version **1.4.1** to fix this issue.

Just run `npm install @oracle/suitecloud-unit-testing` from the root of your sutiecloud project to update the dependency. The update will fix the problem.
