### ISSUE TITLE
Account Configuration Deployment Issue because Multi Location is not enabled. 

### ISSUE THREAD

**Issue by purnagadde** [oracle/netsuite-suitecloud-sdk#757]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.8.0

### Operating system

macOS Ventura 13.5

### Node Version / VSCode Version

Node.js: 16.17.1/VSCode Version: 1.81.1

### JAVA Version

java 17.0.5+9-LTS-191

### Bug description

I get an error when deploying the Accounting Configuration into a fresh instance.
***
An error occurred during configuration validation.
Details: Configuration of INVENTORY(Inventory) feature failed with error: Turning on this feature (Inventory) requires enabling the following features.
Multi-Location Inventory
***

The error says I need to enable the Multi-Location Inventory to enable INVENTORY, but I have the "MULTILOCINVT" feature set to be enabled in the configuration file.

<img width="630" alt="image" src="https://github.com/oracle/netsuite-suitecloud-sdk/assets/17008600/011ad1df-5542-4898-8700-8db688b30d85">

### Steps To Reproduce

1. When running `suitecloud project:deploy`
2. In an account where when trying to enable `INVENTORY` and `MULTILOCINVT` with the same configuration file.

**Comment by alii-gator** [comment]
@purnagadde I was analysing the issue, and there is nothing to be done from the tools perspective. 
Please contact NetSuite Support with this, and they will be able to help you.
