### ISSUE TITLE
Non-public Saved Search Deployment Overwrites 'audslctrole' with Deploying Employee's Role

### ISSUE THREAD

**Issue by poupouproject** [oracle/netsuite-suitecloud-sdk#760]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

v1.5.1

### Operating system

Windows 11 Entreprise 22H2

### Node Version / VSCode Version

Node.js: 18.15.0 / VSCode: 1.82.2

### JAVA Version

17.0.5

### Bug description

When deploying using VSCode and Suitecloud CLI, the "saved search" does not retain the role values in the audience. The value in the "audslctrole" field gets replaced by the role of the employee deploying when the search is not public (ispublic = F). This makes deploying saved searches through the module unusable without manual intervention.

### Steps To Reproduce

1. Create a "saved search" in NetSuite with specific role values set in the audience.
2. Ensure that the search is not set to public (ispublic = F).
3. Deploy the saved search using VSCode with Suitecloud extension.
4. Alternatively, deploy the saved search in a pipeline using Suitecloud CLI.
5. After deployment, check the "audslctrole" field in the saved search.
6. Observe that the original role values in the audience have been replaced by the role of the employee who deployed.

### Actual Output

After deploying the saved search, the "audslctrole" field values are replaced by the role of the deploying employee, regardless of the original role values set in the audience.

### Expected Output

The "audslctrole" field should retain the original role values set in the audience role, regardless of who deploys the saved search.

### Anything else?

Tested in NetSuite environments 2023.1 and 2023.2.
Issue persists both when deploying through Suitecloud extension in VSCode and in a Azure DevOps pipeline with Suitecloud CLI.

**Comment by lfpvillegas** [comment]
Hi @poupouproject 
The case you are describing it's not directly related with the Suitecloud CLI or the VsCode extension but with the Suitecloud Development Framework which is no part of this GitHub repository.
Please contact NS support to report this case, so it could be properly tracked and addressed.
Kind regards
