### ISSUE TITLE
Getting Access Denied on uploading js file to SuiteScript sub folder

### ISSUE THREAD

**Issue by glewisformsol** [oracle/netsuite-suitecloud-sdk#762]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

1.5.1

### Operating system

Windows 11 22H2

### Node Version / VSCode Version

18.15.0

### JAVA Version

java 17.0.6+9-LTS-190

### Bug description

I have a project in VS Code that I can deploy to our production environment, but not the sandbox.  If I remove the path for files in the deploy.xml file I can deploy.  But when I try to deploy the JS file I have I get an Access Denied.

We have SSO enabled on our System.   When I go to create the Access Token, even though my account has the regular Administrator Role assigned it doesn't list it.  I cannot bind the Access Token to my user account and the administrator role and the SuiteCloud Development Integration.  

What should I do to fix this, this issue started right after the new Release of NetSuite and we refreshed our sandbox which revoked all the existing tokens in the sandbox.  But now I cannot recreate the Access Token as explained above.  

I can edit the files inside of the File Cabinet with the other Developer Role we created, but when the deployment tries to upload I think it is getting an access denied error. 

The File cabinet path is : SuiteScripts\FS 

If I can provide anything else please let me know. 

Thank you for your help.

### Steps To Reproduce

1: SuiteCloud: Deploy Project

### Actual Output

2023-10-23 15:50:28 - Project Items
The deployment process has encountered an error.
Deploying to XXXXXX_SB1 - SB1 - XXXXXXXX, LLC - XXXXXXX- Administrator.
2023-10-23 12:49:56 (PST) Installation started
Info -- Account [(SANDBOX) SB1 - XXXXXXXXXXX, LLC]
Info -- Account Customization Project [ProjectItems]
Info -- Framework Version [1.0]
Validate manifest -- Success
Validate deploy file -- Success
Validate configuration -- Success
Validate objects -- Success
Validate files -- Success
Validate folders -- Success
Validate translation imports -- Success
Validation of referenceability from custom objects to translations collection strings in progress. -- Success
Validate preferences -- Success
Validate flags -- Success
Validate for circular dependencies -- Success
Validate account settings -- Success
Validate Custom Objects against the Account -- Success
Validate file cabinet items against the account -- Success
Validate translation imports against the account -- Success
Validation of references to translation collection strings against account in progress. -- Success
Begin deployment
Update object -- custform_fs_project_form (entryform)
Update object -- custform_fs_project_item_form (entryform)
Update object -- custtab_project_item_subtab (subtab)
Update object -- customlist_mhi_material_type_list (customlist)
Update object -- customrecord_fs_project_item (customrecordtype)
Update object -- customrecord_fs_project_item_demand (customrecordtype)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_project_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_item_code (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_item_name (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_item_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_item_description (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_unit_type_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_unit_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item.custrecord_fs_pi_material_type_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item_demand.custrecord_fs_pid_project_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item_demand.custrecord_fs_pid_project_item_id (customrecordcustomfield)
Update object -- customrecord_fs_project_item_demand.custrecord_fs_pid_demand_date (customrecordcustomfield)
Update object -- customrecord_fs_project_item_demand.custrecord_fs_pid_quantity (customrecordcustomfield)
Update object -- customrecord_fs_project_item_demand.custrecord_fs_pid_is_fulfilled (customrecordcustomfield)
Update object -- custentity_fs_prj_location_id (entitycustomfield)
Update object -- custrecord_fs_idp_project_id (othercustomfield)
Update object -- customscript_fs_project_item_demand (usereventscript)
Update object -- customscript_fs_project_item_demand.customdeploy_fs_project_item (scriptdeployment)
*** ERROR ***

An unexpected error has occurred.
Details: Access denied

2023-10-23 12:50:28 (PST) Installation FAILED (0 minutes 32 seconds)

**Comment by davidecorreu** [comment]
Hi @glewisformsol 

I don't have SandBox account, but I can't create administrator tokens in regular production accounts depending how I try to create them.
The way that works for me is to be logged as Administrator and follow the **Manage Access Tokens** link that appears on the main home screen.
From there I'm capable of creating a new token with Administrator role.
![image](https://github.com/oracle/netsuite-suitecloud-sdk/assets/20229175/988ceac0-49fc-4135-ae42-6ef96c4693a6)

Let us know if this works for you.

**Comment by alii-gator** [comment]
Closing because of no response!
