### ISSUE TITLE
Cannot share credentials between WSL and WIndows

### ISSUE THREAD

**Issue by manueltoniato** [oracle/netsuite-suitecloud-sdk#764]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.8.0

### Operating system

Windows 11 - WSL2 with Ubuntu 22.04

### Node Version / VSCode Version

v18.18.2

### JAVA Version

openjdk 17.0.8.1+1-Ubuntu-0ubuntu122.04

### Bug description

In my previous PC with Windows 10, I managed to share the Suitecloud Accounts between Windows and WSL by using the same folder .suitecloud-sdk (in linux I created a symbolic link to the Windows folder).
Now after moving to a new PC with Windows 11 I cannot do this anymore. My credentials works perfectly under WSL (and using Visual Studio Code under WSL) but in Windows I receive the message 
"The following file may be corrupted: C:\Users\mtoniato\.suitecloud-sdk\credentials. Delete it and set up your account again. The authentication IDs you had set up previously will be lost."
Same version of node (18.18.2), same version of suitecloud (1.8.0).

### Steps To Reproduce

1. Share the .suitecloud-sdk between Windows and WSL
2. Try to use the credentials in both environments (for example: suitecloud account:manageauth -i)

### Actual Output

The following file may be corrupted: C:\Users\mtoniato\.suitecloud-sdk\credentials. Delete it and set up your account again. The authentication IDs you had set up previously will be lost.

### Expected Output

? Select an authentication ID (a custom alias you give to a specific account-role combination) to see its details: (Use arrow keys)
❯ allys_sandbox_administrator | Administrator @ ALLYS (IT) SRL | 66394-sb1.app.netsuite.com

**Comment by antoniofruci** [comment]
Hello @manueltoniato ,

Starting with version 1.8.0 it's not allowed anymore to share the credential file among machines because of a security enhancement.
You are now required to set-up account once per machine.
