### ISSUE TITLE
Extension v1.5.1 corrupts credential file

### ISSUE THREAD

**Issue by gabrielgortabns** [oracle/netsuite-suitecloud-sdk#767]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

1.5.1

### Operating system

Windows 11

### Node Version / VSCode Version

Node: v18.15.0, VSCode: v1.83.1

### JAVA Version

java 17.0.7+8-LTS-224 or newer

### Bug description

`./.suitecloud-sdk/credentials` gets corrupted with newer extension version. Tested with 1.4.2 and Java 17.0.7, everything works fine, but if Java or Extension is newer version, it corrupts the credentials file.

### Steps To Reproduce

1. execute `suitecloud account:setup -i`
2. errors shows that `./.suitecloud-sdk/credentials` is corrupted

### Anything else?

related: https://github.com/oracle/netsuite-suitecloud-sdk/issues/716

**Comment by antoniofruci** [comment]
Hello @GabrielGorta,
latest published version version is [1.5.1](https://marketplace.visualstudio.com/items?itemName=Oracle.suitecloud-vscode-extension)
Can you please confirm what's the version you are facing the issue with?

**Comment by GabrielGorta** [comment]
oh, sorry, right, it was version 1.5.1, I misstyped.

**Comment by antoniofruci** [comment]
Starting with version 1.5.0 we have improved the credentials security mechanism. This means that if you use your credentials with any version >1.5.x you won't be able to use them again with any older version. Could this be the case?

**Comment by GabrielGorta** [comment]
Maybe, will test it. Due to other issues our team switch often between newest version and version 1.4.2, that is last that works with ESM + TS template (issue: https://github.com/oracle/netsuite-suitecloud-sdk/issues/765), so it may be the issue. Will try to test it more, what exactly are conditions when credentials file get corrupted.

**Comment by alii-gator** [comment]
@antoniofruci 
The newer version is chnaging how the credentials file is accessed! so first time you upgrade, the tools try to update the saving mechanism of credentials -> This should be a transparent change if everything goes well.
If you downgrade the tools, the credentials gets corrupted.
