### ISSUE TITLE
There was an error when downloading SuiteCloud SDK dependency from https://system.netsuite.com/download/suitecloud-sdk/23.2/cli-2023.2.0.jar

### ISSUE THREAD

**Issue by ppk2017** [oracle/netsuite-suitecloud-sdk#770]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

0.0.0

### Operating system

macOS vertura 13.5.1

### Node Version / VSCode Version

v21.1.0

### JAVA Version

17.0.4.1

### Bug description

No matter run command `sudo npm install -g @oracle/suitecloud-cli`or  'sudo npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli' , always throws up error:

```
npm ERR! minTimeout is greater than maxTimeout

npm ERR! A complete log of this run can be found in: /Users/michaelbao/.npm/_logs/2023-11-10T17_20_17_349Z-debug-0.log
michaelbao@michaelbao-mac ~ % sudo npm config set fetch-retry-maxtimeout 600000                      
michaelbao@michaelbao-mac ~ % sudo npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli

npm ERR! code 255
npm ERR! path /usr/local/lib/node_modules/@oracle/suitecloud-cli
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! There was an error when downloading SuiteCloud SDK dependency from https://system.netsuite.com/download/suitecloud-sdk/23.2/cli-2023.2.0.jar
npm ERR! Error: GET request timeout.
```

### Steps To Reproduce

1. open terminal 
2. run 'sudo npm install -g @oracle/suitecloud-cli'

### Actual Output

npm ERR! minTimeout is greater than maxTimeout

npm ERR! A complete log of this run can be found in: /Users/michaelbao/.npm/_logs/2023-11-10T17_20_17_349Z-debug-0.log
michaelbao@michaelbao-mac ~ % sudo npm config set fetch-retry-maxtimeout 600000                      
michaelbao@michaelbao-mac ~ % sudo npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli

npm ERR! code 255
npm ERR! path /usr/local/lib/node_modules/@oracle/suitecloud-cli
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! There was an error when downloading SuiteCloud SDK dependency from https://system.netsuite.com/download/suitecloud-sdk/23.2/cli-2023.2.0.jar
npm ERR! Error: GET request timeout.

### Expected Output

successful result

### Anything else?

no

**Comment by davidecorreu** [comment]
Hi @ppk2017 ,

Is it possible that you are behind a proxy?
If so, you'll need to setup the **SUITECLOUD_PROXY** environment variable.

Extract from: https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_155929845760.html#Related-Topics
```
 Note:

To configure a proxy server, create the SUITECLOUD_PROXY environment variable.
To be valid, the variable value must include an http or https protocol, a hostname, and a port number,
for example: http://proxyurl:proxyport. After creating the variable, restart the console. 
```

I have also noticed that your node version is **v21.1.0**, and we recommend using **18.14.2 LTS**.

Please don't use `sudo` to install the **SuiteCloud CLI** as it could lead to other future problems as described on this other issue https://github.com/oracle/netsuite-suitecloud-sdk/issues/662#issuecomment-1686329882

**Comment by alii-gator** [comment]
@ppk2017 were you able to try the things mentioned in previous comment?

**Comment by lfpvillegas** [comment]
Closed due to inactivity. 
Please open the ticket again if you still experience the same issue
