### ISSUE TITLE
There was an error when accessing the .suitecloud-sdk/credentials file. Authenticate again to create the file.

### ISSUE THREAD

**Issue by jdvot** [oracle/netsuite-suitecloud-sdk#771]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.8.0

### Operating system

macOs on 14.1.1 (23B81)

### Node Version / VSCode Version

v18.18.2

### JAVA Version

java 17.0.9 2023-10-17 LTS

### Bug description

I used the command "suitecloud account:setup -i" and my terminal returned an error: "There was an error when accessing the .suitecloud-sdk/credentials file. Authenticate again to create the file."

### Steps To Reproduce

1. when running suitecloud account:setup -i 

### Actual Output

There was an error when accessing the .suitecloud-sdk/credentials file. Authenticate again to create the file.

**Comment by davidecorreu** [comment]
Hi @jdvot ,

Can you check the permissions/owner for the `~/.suitecloud-sdk` folder?

If its owned by the root user you should check this https://github.com/oracle/netsuite-suitecloud-sdk/issues/662#issuecomment-1686329882 .

**Comment by alii-gator** [comment]
@jdvot Can you please check the solution above and let us know if it works?

**Comment by lfpvillegas** [comment]
Closed due to inactivity
