### ISSUE TITLE
After account moved to release 2024.1, suitecloud cli stopped working

### ISSUE THREAD

**Issue by jpdevrzmz** [oracle/netsuite-suitecloud-sdk#779]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.8.0

### Operating system

macOS 14.2.1 (23C71)

### Node Version / VSCode Version

v18.16.0

### JAVA Version

openjdk 20.0.1

### Bug description

Cannot upload, download, publish files anymore. Commands are returning the following error:

`There was a problem when uploading the file. Details: SuiteTalk endpoint version 2017_1 is no longer supported`

### Steps To Reproduce

1. Run suitecoud account:setup and configure a browser based approach
2. Run suitecloud file:upload -i, select the file from the promt and enter.
3. It returns the prev error messages after few seconds: `There was a problem when uploading the file. Details: SuiteTalk endpoint version 2017_1 is no longer supported`

### Actual Output

<img width="835" alt="image" src="https://github.com/oracle/netsuite-suitecloud-sdk/assets/126217480/cd19ef2b-b218-4ad4-a987-6a9f6a20283f">

**Comment by starlingjon** [comment]
Also seeing this with CLI version 1.8.0, coworkers using the WebStorm plugin (version 2023.2.0) are seeing the same issue (cannot upload to a 2024.1 account because "SuiteTalk endpoint version 2017_1 is no longer supported")

**Comment by lfpvillegas** [comment]
Hello @jpdevrzmz  and @starlingjon .

We are aware of this issue. We are going to release a new version of the tools soon that won't show this message. We will notify you when it is available.
In the meanwhile, you could use deploy as a workaround or upload the files using the UI.

Thanks for reporting

**Comment by jpdevrzmz** [comment]
Hi @lfpvillegas - thanks for taking care of it. Does your team have an expected date to release the fix?

**Comment by lukaszcoff** [comment]
I found temporary workaround - you can still deploy projects, just limit the deployment to file(s) you need to be uploaded.

**Comment by LukaszFormela** [comment]
I found temporary workaround - you can still deploy projects, you just need to limit the deployment to file(s) you want to upload.

**Comment by Erp-NetSuite** [comment]
Upvoting this issue here....

I noticed this issue in Release Preview instance, I hope same wouldn't be rolled to Production once it is upgraded to 2024.1.

**Comment by mgrezak** [comment]
Upvoting this issue here as well.

Hope fix comes in time...

**Comment by jpdevrzmz** [comment]
@Erp-NetSuite, @mgrezak - Certainly, I have engaged in discussions with numerous developers from various companies, and it is becoming evident that this issue is significantly hindering business operations... cc: @lfpvillegas

**Comment by lfpvillegas** [comment]
Hi @jpdevrzmz .
The fix is ready to be released with the next NetSuite E-fix. Hopefully it would be available in the following days. We will notify you.
Meanwhile you could use the workaround described before (use of deploy command)

**Comment by mgrezak** [comment]
> Noticed a 2023.2.0 → 2024.1.0 update to the SuiteCloud IDE Plug-in for Webstorm but it fails to download it from the NetSuite ENG repo (see error message below): Plugin "SuiteCloud IDE Plug-in for WebStorm" was not installed: Cannot download 'https://repository.eng.netsuite.com/content/repositories/suitecloud-sdk/release_candidates/24.1/webstorm/com.netsuite.ide.webstorm.app-2024.1.0.zip': repository.eng.netsuite.com
> 
> The notice to upgrade is coming from the https://system.netsuite.com/download/suitecloud-sdk/ideplugin/webstorm/latest/updatePlugins.xml custom plugin repository

I tried updating again this morning and the file was successfully downloaded and installed in Webstorm. Using the 2024.1.0  version of the SuiteCloud IDE Plug-in for Webstorm, I tested uploading a file to Release Preview 2024.1 and it was successfully uploaded! No more bug! Thank you

**Comment by starlingjon** [comment]
Looks like CLI version 1.9.0 is available and works as expected too 👍 thanks

**Comment by tourajvaziri** [comment]
The new version of the tool has been released and fixes this issues.
