### ISSUE TITLE
JAR file not available

### ISSUE THREAD

**Issue by sirvine-r7** [oracle/netsuite-suitecloud-sdk#793]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.7.3

### Operating system

Alpine Linux

### Node Version / VSCode Version

20.10.0

### JAVA Version

17.0.10_p7-r0

### Bug description

Getting below JAR file not found error when using version 1.7.3
Updating to 1.9.0 resolved the issue.

```
[0m[91mnpm ERR![0m[91m There was an error when downloading SuiteCloud SDK dependency from https://system.netsuite.com/download/suitecloud-sdk/23.1/cli-2023.1.0.jar
[0m[91mnpm ERR! The JAR file is not available from this URL.
[0m[91m
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-12T11_25_46_422Z-debug-0.log
[0mService 'suitecloud-deploy' failed to build : The command '/bin/sh -c npm install --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli@1.7.3' returned a non-zero code: 255
```

### Steps To Reproduce

1. Try to install the 1.7.3 version of CLI too

**Comment by alii-gator** [comment]
Hello, why are you trying to install 1.7.3 specifically?
you should run `npm install -g @oracle/suitecloud-cli` and it will download the latest version available!

**Comment by sirvine-r7** [comment]
Because we couldn't trust the latest versions to not have breaking changes, so now we test versions and lock in the version number. We're happy to update to newer versions we just need a heads up when there's breaking changes like the jar file moving.

Per: https://github.com/oracle/netsuite-suitecloud-sdk/issues/746#issuecomment-1680263219

**Comment by lfpvillegas** [comment]
Hi @sirvine-r7 .
We remove versions that are more than one year old. That means that we maintain the downloads of two past versions. 
Right now, we have updated new version 1.9.0 so we maintain previous 1.8.0 version and we have removed 1.7.3.

Doing this, we ensure compatibility with leading and lagging versions of NetSuite and that you have enough time to migrate to new versions. Also, we have time for fixing breaking changes whenever they appear and release the fix.
Please update to the latest version whenever it's possible.
Thanks
