### ISSUE TITLE
Something went wrong when trying to save credentials. Contact support.

### ISSUE THREAD

**Issue by dbeastes** [oracle/netsuite-suitecloud-sdk#800]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

1.6.0

### Operating system

Windows 11

### Node Version / VSCode Version

1.81.1

### JAVA Version

17.0.2+8-LTS-86

### Bug description

Recieving error "Something went wrong when trying to save credentials. Contact support." when trying to remove or create account set up.

### Steps To Reproduce

1. Run Manage Accounts
2. Select account to remove.
3. getting error "Something went wrong when trying to save credentials. Contact support." 

### Actual Output

Getting Error "Something went wrong when trying to save credentials. Contact support."

### Expected Output

Account should be removed.

**Comment by antoniofruci** [comment]
Hi @dbeastes ,
Can you confirm you are able to see **ALL** the previously set-up accounts and the error only happens when trying to add or delete?

**Comment by dbeastes** [comment]
Hi @antoniofruci,
Yes. All other functionality seems to be working. I had to update the sdk earlier this week to account for a NetSuite 2024.1 release not allowing me to upload files. After the update, everything seemed to be working, but now I get this error trying to write to the credentials file. Setting up a new account or even removing or renaming an account gives the same error. I tried removing the credentials file and setting up a new account. It did recreate the file, but the file remained empty and I still got the error. I can update the credentials file manually. Is there something in the SDK that I need to give permission?

**Comment by alii-gator** [comment]
@dbeastes can you please try to run the following on your command line and share the format of the output, you dont have to share the actual output.
`wmic csproduct get UUID`

**Comment by dbeastes** [comment]
Hello @alii-gator, 
I get this error: "The term 'wmic' is not recognized as the name of a cmdlet, function, script file, or operable program."

But maybe I'm doing it wrong.

**Comment by RSCMal** [comment]
Any luck with a solution?

I'm having the same issue. I've tried just about everything I can think of to resolve the issue. 
* Uninstalled / Reinstalled various versions of WebStorm
* Deleted the credentials file
* CLI / Node.js
* New Windows Profile

It's only happening on one computer. Initially rolled back to older plugin, 2023.1, but that's broken and no longer available.

**Comment by alii-gator** [comment]
@dbeastes @RSCMal 
Can you please try following steps

```
Open Settings by pressing the Windows + I keys together.
Then, chooses apps Then, click Optional features.
Click the Feature display button.
Search for Wmic and check the box next to it and press Next.
Click the Install/enable button.
```

Enabling above might take a while, when its enabled please restart your machine and try the following in CMD
`wmic csproduct get UUID`

If this gives you an output, please try running the latest version of suitecloud extension, it should work

**Comment by RSCMal** [comment]
wmic is installed for me. I'm getting the following error when I run this command. 

ERROR:
Description = Invalid namespace

Further research indicates that the WMI database is corrupt, so I've rebuilt it and now this command returns a UUID

I'm no longer getting the error in Webstorm.

**Comment by Sreebalar2407** [comment]
Hi I am getting the below error when I try to Setup a new Account in Visual studio for SuiteCloud
2025-02-07 11:04:11 - SDF_SB1
Something went wrong when trying to access credentials. Contact support.
