### ISSUE TITLE
Can't install script XML with INVENTORYDETAIL recordtype

### ISSUE THREAD

**Issue by sparco707** [oracle/netsuite-suitecloud-sdk#803]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

v1.6.0

### Operating system

Windows 11

### Node Version / VSCode Version

v16.17.1 / 1.88.1

### JAVA Version

java 17.0.4.1+1-LTS-2

### Bug description

I have a script XML file with INVENTORYDETAIL in recordtype tag. This fix was exported from my NetSuite account script record. Nothing was changed manually. However, when I'm trying to install this XML via SDF, I receive error:
" The recordtype field for the customdeploy_xxxxxxx (scriptdeployment) subrecord must not be INVENTORYDETAIL"

### Steps To Reproduce

1. Create script file with INVENTORYDETAIL recordtype deployment
2. Run suitecloud project:deploy

### Actual Output

Error
"The recordtype field for the customdeploy_xxxxxxx (scriptdeployment) subrecord must not be INVENTORYDETAIL"

### Expected Output

Deployment successfull

**Comment by davidecorreu** [comment]
Hi @sparco707 ,

First of all sorry for the late reply.

This platform is for reporting bugs related to SuiteCloud CLI for NodeJS, SuiteCloud Extension for VSCode and SuiteCloud Unit Testing.

The behavior you have described is not related to the tools it self but with SDF (SuiteCloud Development Framework) Functionality.  In this case the SuiteCloud CLI is just showing the output returned by SDF server-side response.

Please contact NetSuite support to report this case.
