### ISSUE TITLE
Support account:setup in a non interactive mode

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#81]
Currently the account:setup command is marked with a _forceInteractiveMode_ flag.
It would be great if it will support also a non interactive mode to enable calling it using JS in one shot.

**Comment by alii-gator** [comment]
This feature enhancement is already under consideration. We are currently evaluating different options/approaches. Thanks for bringing this up.

**Comment by omrilit** [comment]
@alii-gator do you have any rough estimation when it will be implemented?

**Comment by alii-gator** [comment]
@omrilit Unfortunately at this point we are not able to give any estimate. But it's something we are actively looking into. So stay tuned for any updates on this.

**Comment by bretislav** [comment]
any update on this please?

**Comment by adamkundrat** [comment]
this is very stupid, I don't understand how you could not consider it in an initial stage. It makes the tool useless for any automation tool.

**Comment by colivares82** [comment]
@omrilit , this is already in our backlog and it will be as soon as we can deliver it, this is the first iteration of this tool and we are working to improve the experience. Thank you for sharing this need, it definitely validates implementation and it will be there.

**Comment by colivares82** [comment]
@bretislav , We will release the update as soon as we get it done. We are working in our release cycles and since this is the first time for us to expose a product as open-source, we still need to align some processes before pushing changes as fast as it might be expected. Thanks for the patience, we will improve in time.

**Comment by colivares82** [comment]
@adamkundrat I guess that you can read what I expose above, and please the next time do not refer to our efforts as something stupid. If you have questions or suggestions, they can be done in another tone.  For what it worth, this is the first version of something completely new and we are aware of this opportunity of improvement, it will be solved as soon as possible.

**Comment by alii-gator** [comment]
@omrilit 
This is now fixed/available in latest version 
get the latest npm package version `1.1.0`
checkout` account:ci` command

**Comment by bretislav** [comment]
1.1.0 is a massive improvement. Good work and thanks!
