### ISSUE TITLE
Issue on upload a folder

### ISSUE THREAD

**Issue by Davidna92** [oracle/netsuite-suitecloud-sdk#833]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.2.0

### Operating system

Windows 11

### Node Version / VSCode Version

v20.10.0

### JAVA Version

java 17.0.5+9-LTS-191

### Bug description

I cannot update entire folder, its always ask me for a specific files.
For example I have this structure:

src > 
      FileCabiner >
                        SuiteScripts >
                                            Folder One >
                                                       Folder Two >
                                                                       Script 1
                                                                       Script 2
                                                                       Script 3
                                                                       
                                                                       
In Webstom suite cloud, when I click Ctrl + Shift  + U I can update an entire folder, for example -  Folder Two and its files.   
But here, in vscode it ask me to choose specific files to upload. 
How can I achieve that?
                                                                    

### Steps To Reproduce

1. When trying to update a folder/file

**Comment by alisyed-19** [comment]
@Davidna92 Its not exactly the same in webstorm but in CLI, you can select the folder you want to update, then it shows you all the files of that folder.
You can select all files by pressing `a` on the keyboard

**Comment by Davidna92** [comment]
How do I open the CLI ? this is not the extension  ?

**Comment by Davidna92** [comment]
What is the command to update from CLI? (I used the UI method...)

**Comment by alisyed-19** [comment]
@Davidna92 you can see all available command by just executing `suitecloud`
The command to upload files is `suitecloud file:upload -i`
