### ISSUE TITLE
Error when calling account:setup:ci "Unexpected error. Verify the certificate file"

### ISSUE THREAD

**Issue by caleb** [oracle/netsuite-suitecloud-sdk#834]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

2.0.0

### Operating system

macOS Sonoma 14.5

### Node Version / VSCode Version

v16.14.2

### JAVA Version

openjdk 21.0.2+13-58

### Bug description

I am following the instructions on [https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_162686838198.html#subsect_162686947286](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_162686838198.html#subsect_162686947286) to create a private/public key pair to use to authenticate with the new `account:setup:ci` command in suitecloud-cli and am getting the error: 

```
Unexpected error. Verify the certificate file /Users/caleb/Projects/suitecloud/private.pem.
```

I generated the certificate with this command:

```bash
openssl req -new -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes -days 365 -out public.pem -keyout private.pem
```

The command I'm running is:

```bash
suitecloud account:setup:ci --account XXXXXXX --authid "sandbox" --certificateid "<CERTIFICATE ID>" --domain XXXXXXX-sb1.app.netsuite.com --privatekeypath private.pem
```

The `CERTIFICATE ID` is from the "OAuth 2.0 Client Credentials Setup" page in my NS instance

### Steps To Reproduce

1. Create an public/privatey key pair according to the NS instructions: https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_162686838198.html#subsect_162686947286
2. Upload the public key to the "OAuth 2.0 Client Credentials Setup" page (https://XXXXXXX-sb1.app.netsuite.com/app/oauth2/clientcredentials/setup.nl)
3. Use the `suitecloud account:setup:ci` command with the generated private key

### Actual Output

Unexpected error. Verify the certificate file /Users/caleb/Projects/suitecloud/private.pem.

### Expected Output

I expect `suitecloud` to setup my project to be used with the suitecloud CLI

**Comment by caleb** [comment]
I found that generating an RSA key worked:

```
openssl req -x509 \
            -newkey rsa:4096 \
            -sha256 \
            -keyout private.key \
            -out public.pem \
            -noenc 
```

I also found that I had to specify my sandbox account id with the "SB-1" suffix: `XXXXXXX_SB1`. This is different from the previous version if I recall correctly.

**Comment by alisyed-19** [comment]
@caleb Glad you found the solution.
Regarding the "SB_1" in account ID, it has always been like this.

**Comment by SkylerStingray** [comment]
I too am having the same issue as caleb even with usage of an RSA key as described. I followed all of the same steps and still get a `Unexpected error. Verify the certificate file /Users/swittman/.netsuite/private.pem.` error.

Anything else that you did @caleb to make this functional?
Thanks

**Comment by SkylerStingray** [comment]
Never mind, this comment from another issue solved my problem: https://github.com/oracle/netsuite-suitecloud-sdk/issues/853#issuecomment-2377048267
