### ISSUE TITLE
The "account:savetoken" command does not exist. Run "suitecloud" to see the supported commands.

### ISSUE THREAD

**Issue by 786country** [oracle/netsuite-suitecloud-sdk#835]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

2.0.0

### Operating system

amazoncorretto:17-alpine

### Node Version / VSCode Version

v20.16.0

### JAVA Version

17

### Bug description

Well I see that the command is not working with the new release but also your documentation states that 2024.2 release notes are out but the link shows only information on 2024.1 

Read the release notes for NetSuite 2024.2 in [SuiteCloud SDK Release Notes](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1558730192.html).

So where do I look for documentation?

### Steps To Reproduce

N/A

**Comment by johncyig** [comment]
I'm also running into the same issue.

**Comment by alisyed-19** [comment]
We are working on making the docs available for accounts still on 24.1 version
Meanwhile use these docs for reference 
[SuiteCloudCLINodejs.pdf](https://github.com/user-attachments/files/16619368/SuiteCloudCLINodejs.pdf)
[SuiteCloudExtensionforVSCode.pdf](https://github.com/user-attachments/files/16619369/SuiteCloudExtensionforVSCode.pdf)
[SuiteCloudSDKOverview.pdf](https://github.com/user-attachments/files/16619370/SuiteCloudSDKOverview.pdf)
