### ISSUE TITLE
Authentication IDs Lost

### ISSUE THREAD

**Issue by joshbrox** [oracle/netsuite-suitecloud-sdk#837]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

2.0.0

### Operating system

macOS Ventura 13.6.9

### Node Version / VSCode Version

1.92.2 (Universal)

### JAVA Version

java version 'java 17.0.9+11-LTS-201'

### Bug description

All my credentials were lost. I now get this error message when clicking SuiteCloud: Set Up Account.

"Some of your authentication details are not compatible with the current version of this SuiteCloud SDK tool. Delete the /Users/joshbrox/.suitecloud-sdk/credentials file to proceed. The authentication IDs you set up previously will be lost. Ensure that you update all the SuiteCloud SDK tools to the latest version."

### Steps To Reproduce

Click SuiteCloud: Set Up Account

### Actual Output

Some of your authentication details are not compatible with the current version of this SuiteCloud SDK tool. Delete the /Users/joshbrox/.suitecloud-sdk/credentials file to proceed. The authentication IDs you set up previously will be lost. Ensure that you update all the SuiteCloud SDK tools to the latest version.

### Expected Output

Show account credentials and be able to update files using saved credentials.

**Comment by alisyed-19** [comment]
@joshbrox This is expected. You should go to path shown in error message and delete the file. When you run the command again after deleting you will be able to continue.
You should see all info in help docs if you are on 24.2 version, if you are still on 24.1, you will see the info in help center on Monday.

Meanwhile check the PDFs info [here](https://github.com/oracle/netsuite-suitecloud-sdk/issues/835#issuecomment-2289993586)
