### ISSUE TITLE
Manage Auth: Null pointer exception

### ISSUE THREAD

**Issue by thomasync** [oracle/netsuite-suitecloud-sdk#842]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

1.9.0

### Operating system

Sonoma 14.6.1

### Node Version / VSCode Version

v20.16.0

### JAVA Version

openjdk 17.0.12+0

### Bug description

When I try to get information about an authentication via its ID

### Steps To Reproduce

1. Listing

- ❯ suitecloud account:manageauth --list
**7967400_SB-Adm-Sand | Administrator @ Enterprise**

2. Get informations

- ❯ suitecloud account:manageauth --info "7967400_SB-Adm-Sand | Administrator @ Enterprise"
**Internal error encountered (Null pointer exception).**

- ❯ suitecloud account:manageauth --info "7967400_SB-Adm-Sand"
**Internal error encountered (Null pointer exception).**

**Comment by alisyed-19** [comment]
@thomasync Did you upgrade to 2.0.0 and then downgraded back to 1.9.0?

**Comment by alisyed-19** [comment]
@thomasync If you are using more that 1 suitecloud tools please upgrade them all to latest available versions. Delete the credentials file and generate a new authids. This should fix the problem.
