### ISSUE TITLE
[Not from Docker] Something went wrong when trying to access credentials. Contact support.

### ISSUE THREAD

**Issue by kostiato** [oracle/netsuite-suitecloud-sdk#843]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud CLI

### Version of the SuiteCloud Tool

cli-2024.1.0.jar, cli-2024.2.0.jar

### Operating system

Artix Linux 6.10.6-artix1-1 (64-bit)

### Node Version / VSCode Version

Do not use

### JAVA Version

java 17.0.12+8-LTS-286, openjdk 17.0.12+7

### Bug description

The issue is with SuiteCloud CLI for Java itself. I'm not sure if it is legit to post it here. Anyways,...

2024.1.0 opens browser but fails after successful authentication: 
```
$ java -jar ~/sdf-cli/cli-2024.1.0.jar authenticate -authid example
Authenticating...
The TBA token was successfully issued in NetSuite.
Something went wrong when trying to save credentials. Contact support.
```
2024.2.0 does nothing 
```
$ java -jar ~/sdf-cli/cli-2024.2.0.jar authenticate -authid example
Something went wrong when trying to access credentials. Contact support.
```
Tried both with Oracle JDK and OpenJDK. No luck.
Tried with new user profile. No luck.
I have removed `~/.suitecloud-sdk/` and `~/.sdf` and tried several times. No luck.
I can't find any more details about the error. Only "Something went wrong..." message appears in `~/.sdf`
I'm open to help debugging and provide more details.

P.S. 
Funny thing is that 2023.2.0 works good on the same machine with the same setup. 
I have never had any issues with previous versions too.

### Steps To Reproduce

`sdfcli authenticate -authid authid` just does not work

**Comment by alisyed-19** [comment]
@kostiato Thanks for reporting.
So, you are not reporting this for docker. But you have tried to run this in terminal in your OS?

https://github.com/oracle/netsuite-suitecloud-sdk/issues/746#issuecomment-1683907712
Seems like your OS is missing `dbus-uuidgen`

**Comment by kostiato** [comment]
it doesn't seem so
```
$ dbus-uuidgen --version
D-Bus UUID Generator 1.14.10
Copyright (C) 2006 Red Hat, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by davidecorreu** [comment]
Hi @kostiato ,

Does any of these 2 shell commands giving you some output?
1. `cat /var/lib/dbus/machine-id`
2. `hostnamectl`

Could you share its output (obscuring any 32hex string appearing on it).

**Comment by kostiato** [comment]
@davidecorreu thanks for jumping in
I don't use systemd as init service, so `hostnamectl` doesn't exist.
I don't have `dbus` directory inside `/var/lib/`
