### ISSUE TITLE
Can't Setup account on version v2.0.0 and v2.0.1

### ISSUE THREAD

**Issue by pcavendano** [oracle/netsuite-suitecloud-sdk#853]
### Select the SuiteCloud tool where you encountered the issue

SuiteCloud Extension for VSCode

### Version of the SuiteCloud Tool

2.0.1

### Operating system

Windows 10 and Windows 11 version 23H2

### Node Version / VSCode Version

v20.17.0

### JAVA Version

java 17.0.12 2024-07-16 LTS

### Bug description

While setting up OAuth 2.0 Client Credentials after update i keep getting diferent errors related to not being able to set up account or access the credentials with either the cli and the extension. Other operations like Create Project seem to work.

<img width="666" alt="{22419821-D02F-488A-BEE3-0249146A81B8}" src="https://github.com/user-attachments/assets/95f8b3f5-76a7-44de-bec6-3a446cacc984">

### Steps To Reproduce

1.- On VSCODE, click on Setup account

### Actual Output

<img width="404" alt="{EF2D2161-3317-4E8E-9018-D711D21B85AE}" src="https://github.com/user-attachments/assets/4652c356-ee4c-4d15-9d67-6219e5a10c9f">

### Expected Output

New Window that allows you to set up your account

### Anything else?

This behavior also happens when using the cli

**Comment by davidecorreu** [comment]
Please share the OUTPUT of  **SuiteCloud** shown after clicking on the **See Details** button of your screenshot.

**Comment by pcavendano** [comment]
Some of your authentication details are not compatible with the current version of this SuiteCloud SDK tool. Delete the C:\Users\Cambridge\.suitecloud-sdk\credentials file to proceed. The authentication IDs you set up previously will be lost. Ensure that you update all the SuiteCloud SDK tools to the latest version. I did that i now i got pass that part, my issue now is this message, Unexpected error. Verify the certificate ID and check that it has not expired. when i run suitecloud account:setup:ci --account {{account}} --authid {{name}} --certificateid {{certificate}} --privatekeypath private.pem. I created my key using this command,             openssl req -new -x509 -newkey rsa:4096 -keyout private.pem -sigopt rsa_padding_mode:pss -sha256 -sigopt rsa_pss_saltlen:64 -out public.pem -nodes 

<img width="494" alt="{FDC1B387-6E68-4C29-BB70-8107D3E982F3}" src="https://github.com/user-attachments/assets/7329a870-7dff-4eeb-b6a9-cd608adf5cc8">

I'm using powershell

**Comment by carolnavarropereira** [comment]
Hi, Pedro.
Is it possible for you to try to generate and try with a new certificate just to make sure?
Also, could you check the integration record (the OAuth 2.0 Client Credentials Setup)
how many certificates do you have? can you show us a screenshot? you may blur the certificate Id so it is not readable

**Comment by pcavendano** [comment]
Hi Carol, I fixed my issue. I was mistakenly choosing the wrong application in the menu below. After carefully reading the documentation, I found a section that mentioned the role needs to be a developer role and that I should select the Suite Development application. I had created an integration myself and was trying to connect SDF with that newly created integration, I think I got lost at some point in all the documentation.
![image](https://github.com/user-attachments/assets/0a87f6df-e979-4517-a9d9-b80f5b8bed6c)

**Comment by pcavendano** [comment]
This error occur because i wrongly chose an Integration that i created instead of the SuiteCloud Development Integration

**Comment by carolnavarropereira** [comment]
We are happy you got your problem solved.

**Comment by SkylerStingray** [comment]
Thank you so much @pcavendano. This just solved my problem after many many hours of trial and error and reading through netsuite documentation.
I'd recommend to any dev reading this to please highlight this better in the docs that it can't be a custom integration.

Thank you

**Comment by isaacmontano17** [comment]
> Hi Carol, I fixed my issue. I was mistakenly choosing the wrong application in the menu below. After carefully reading the documentation, I found a section that mentioned the role needs to be a developer role and that I should select the Suite Development application. I had created an integration myself and was trying to connect SDF with that newly created integration, I think I got lost at some point in all the documentation. ![image](https://github.com/user-attachments/assets/0a87f6df-e979-4517-a9d9-b80f5b8bed6c)

THIS! Thank you so much for commenting this. I did the same exact thing and wasted a whole day trying to figure out what I was doing wrong.

**Comment by raghucrm** [comment]
This is helpful
