### ISSUE TITLE
Add stubs for all native Suitescript N/ modules. 

### ISSUE THREAD

**Issue by hntejas** [oracle/netsuite-suitecloud-sdk#86]
Hi maintainers,

request you to add stub support to all existing suitescript N/ modules. 

Thanks

**Comment by alii-gator** [comment]
@hntejas Thanks for bringing this up. This is already on our roadmap, but this will not happen at once. The stubs will be added gradually.
In mean while you can add custom stubs of the modules you use heavily. The information is provided on how to do that in read.me files and NS help docs.

**Comment by hntejas** [comment]
@alii-gator Thanks for the info. We are using custom stubs. I will look forward to the future release for stubs.
