### ISSUE TITLE
Node.JS 13 doesn't work due to node-sass dependency

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#91]
As stated in the attached screenshot (taken from https://www.npmjs.com/package/node-sass), the node-sass version used in the project, 4.12.0, doesn't support node 13. ![image](https://user-images.githubusercontent.com/9881966/79123476-ee099200-7da2-11ea-9443-a17164f77616.png)

**Comment by colivares82** [comment]
Thank you @omrilit.

**Comment by colivares82** [comment]
To be considered when Node Version gets updated as our dependency
