### ISSUE TITLE
Support log file generation for project:validate and project:deploy

### ISSUE THREAD

**Issue by dylan-glenn** [oracle/netsuite-suitecloud-sdk#93]
In the Java version of the SuiteCloud CLI, the validate and deploy commands support the option to generate a log file to a specific directory.

Does the Node.js version support this functionality? If so, how is it achieved? If not, is this on the roadmap for this tool?

**Comment by vic-nik** [comment]
@dylan-glenn Thank you for the feedback.
This is not currently supported by SuiteCloud CLI but we are considering adding log option to project:deploy and project:validate commands. We will keep this issue open until we have more updates on the progress.

**Comment by dylan-glenn** [comment]
Thanks for the response!

For those interested, I was able to replicate this functionality with a custom bash script.

**Comment by alii-gator** [comment]
@dylan-glenn This is fixed and hopefully will be available in our upcoming release.

**Comment by alii-gator** [comment]
@dylan-glenn 
This is now fixed/available in latest version 
get the latest npm package version `1.1.0`
