### ISSUE TITLE
file:import -i Stuck loading File Cabinet folders indefinitely

### ISSUE THREAD

**Issue by Nic-Wolf** [oracle/netsuite-suitecloud-sdk#95]
Starting a new project, and trying to load all existing scripts from the default SuiteScripts/ location.
```
λ suitecloud file:import -i
| Loading File Cabinet folders...
```
This never actually finishes loading. Ran it a number of times, and it'll just get stuck here for at least an hour. There's only about 3MB of files in there, so I don't think it's an issue with the folder size.

**Comment by alii-gator** [comment]
Hi @Nic-Wolf can you please mention the environment where you are running this command?
OS, Node version?
The account is production?

**Comment by Nic-Wolf** [comment]
Yes, I'm attempting this in production. I still have the release preview, and I'm getting the same results there as well.

Windows 10 Enterprise, (64 bit) build 18362
Node v12.16.1
NPM v6.13.6
Java v11.0.7

For the console, I'm using cmder, but I get the same results in powershell. Running both as admin.

**Comment by alii-gator** [comment]
@Nic-Wolf The environment setup looks good.
Are you working behind any proxy? 
All the commands are the same for you or its just **file:import** which is not working.

**Comment by Nic-Wolf** [comment]
Well, I know someone's doing something out there, since I'm now getting an unexpected error instead of an eternal loading message...
```
λ suitecloud file:import -i
The remote server returned an error:

An unexpected error occurred.
```
I should clarify: **file:import** works when the **--paths** parameter contains a specific file. The error occurs when using **-i**. It's not feasible for me to specify each file, nor is it feasible to write a ps script to dive through the whole SuiteScripts folder, downloading things one by one. 

However, since seeing this new error message, I'm not even able to download individual files.

Anyway, ere's the info you requested.
Suitecloud v1.0.2
I'm not behind a proxy.
Yes, I installed as documented: npm install -g @oracle/suitecloud-cli
there were no errors during installation.
I have uninstalled / reinstalled, and used different internet connections and different computers. The results are always consistent.

**Comment by alii-gator** [comment]
@Nic-Wolf I have tried with similar environments and its working for us.
If you are having the same problem, we can have a quick call to check it.

**Comment by colivares82** [comment]
@Nic-Wolf Hello, would you want to have a quick call to go over the process and identify the case?

**Comment by alii-gator** [comment]
Closing it after waiting for answers for a long time.

**Comment by faiwudevse** [comment]
I have the same issue with suitecloud file:import -i that keeps spinning. Like others mention the path option works.

**Comment by mmdonohue** [comment]
If you get stuck here, I created a powershell script that imports from a txt file.
Just copy and paste the output from suitecloud file:list --folder /SuiteScripts into a file _import_files.txt_
save below as import_runner.ps1 in project root and change below  (<_USER_>, <_PROJECT ROOT_>) to your import list path

Get-Content C:\Users\<_USER_>\Documents\<_PROJECT ROOT_>\src\import_files.txt |
  ForEach-Object { suitecloud file:import  --paths $_ }

Output:
![image](https://user-images.githubusercontent.com/7181953/152667607-c83cb8c5-65cb-4887-8207-bb90c18e338f.png)
