### ISSUE TITLE
--excludefiles flag on Object import is ignored

### ISSUE THREAD

**Issue by petterolsen** [oracle/netsuite-suitecloud-sdk#97]
The --excludefiles seems to be ignored on object import.
The following command still produces imports of associated Javascript files. Order of parameters have been tested unsuccessfully.

> suitecloud object:import --destinationfolder "/Objects/temp/" --excludefiles --scriptid ALL --type usereventscript

**Comment by alii-gator** [comment]
@petterolsen Thankyou for the feeback
We are looking into it and hopefully will update you as soon as we have some new about it.

**Comment by alii-gator** [comment]
@petterolsen This is fixed and will be available hopefully in our upcoming release.

**Comment by petterolsen** [comment]
Great news!

**Comment by alii-gator** [comment]
@petterolsen 
This is now fixed/available in latest version 
get the latest npm package version `1.1.0`
